# preface {.unnumbered}

This work-in-progress will ultimately serve as a textbook for introductory undergraduate courses in data sciences, and is particularly aimed at students in the liberal arts. No prior knowledge of computer programming is presumed, though, ideally, students will have had college algebra (or its equivalent) and an introductory course in statistics, methods, or data analysis.

## the book is for you {.unnumbered}

It's our intention that this text should serve *every* college student, regardless of concentration or college major. The skills and insights that you will gain in this course will help you in graduate and professional schools, will help you in your careers, and will help you in your goal of making a better world. And it will help you train the next generation of data scientists as well.

## the role of the liberal arts in data science {.unnumbered}

Since the middle of the 20th Century, we have been living in an age of information, in which global commerce, social communities, and, increasingly, individual identities are all driven more by the movement of electrons than by basic needs for sustenance, agrarian challenges, and manufacturing. To prosper, and even to behave responsibly, in the age of information requires a new form of literacy, one which goes beyond spoken or written language, and even beyond quantitative 'numeracy' [@paulos1988].

Computational literacy is an essential part of a contemporary liberal arts education. (Incidentally, the 'liberal' in liberal arts refers to the intellectual freedom of a liberated mind. The 'arts' refers to skills in disciplines in the humanities, and social and natural sciences). The first course in data science should foster computational literacy among all undergraduates and should provide an invitation or inducement to further study as well.

Data science is still a relatively new field of study - although not as new as when one of us (KL) first wrote this. Then, as now, there are multiple approaches to teaching data science and to situating it in the college curriculum. This book is intended to serve courses such as [*Introduction to Data Science*](https://kevinlanning.github.io/DataSciSpring2025/) at the Wilkes Honors College of Florida Atlantic University which, in turn, was initially based on data science classes including those at the universities of [North Carolina](https://idc9.github.io/stor390/), [British Columbia](https://stat545.com/), [Duke](http://www2.stat.duke.edu/courses/Fall18/sta112.01/), [Maryland](http://www.hcbravo.org/IntroDataSci/calendar/), [Stanford](https://github.com/dcl-2017-04/curriculum), and [Harvard](http://datasciencelabs.github.io/). At each of these schools, the Introduction to Data Science is arguably closer to Statistics than to Computer Science.

Statistics is itself a broad field, and our approach is aligned with its most applied and pragmatic form. From this perspective, the choice of statistical methods should follow from the data and problem at hand - in other words, statistics should serve the needs of the user rather than dictate them [@loevinger1957].

Pragmatism, in turn, can serve various goals, ranging from maximizing the revenues generated by an online ad to minimizing the carbon footprint of a travel itinerary. Data science for the liberal arts may be seen as a fusion of the pragmatism of data science with social and humanistic concerns; we stand beside programs in [Computational Social Science](https://sicss.io/) as it has been taught in places such as [Chicago](https://dssg.uchicago.edu/), [Princeton](http://www.princeton.edu/~mjs3/soc596_f2016/), [UC Berkeley](https://github.com/rochelleterman/PS239T), [Berlin](https://github.com/HertieDataScience/SyllabusAndLectures), and in [Columbia's School of Journalism](https://github.com/tommeagher/data1-fall2015).

In its concern with the liberal arts, it is intended to provide a modest counterbalance to the inherently centripetal, inequality-accelerating, force of modern information technology.[^00-preface-1]

[^00-preface-1]: I hope to return to this in a later chapter, but in the meantime consider the discussion of the "Matthew Effect" in sociology and network science [@watts2004].

## some features of the text {.unnumbered}

There are a number of different approaches to teaching the introduction to data science for the liberal arts. The present text includes several distinguishing features or emphases.

**The R programming language**

We'll use, and explore the advantages and disadvantages, of spreadsheets such as Excel or Google Sheets. But most of our work will be with the R programming language.

About ten years ago, in an informal survey of introductory data science courses, I found a pretty even split between those which began with Python and those which began with the statistical programming language R. This difference corresponds, very loosely, to the split noted above: Computer science based approaches to data science were frequently grounded in Python, while statistics-based approaches were generally grounded in R.

Today, the "R versus Python" debate has become less consequential, in part because the distinction between the two languages has narrowed. Many widely used Python tools are accessible through R interfaces or wrappers. Perhaps more importantly, advances in AI-assisted coding have made syntactical differences between the languages much less of a barrier to learning and use.

Python has its place. That language is the dominant base for coding in engineering, computer science, and related areas where programming, algorithm development, and large-scale analysis are central concerns. R remains the coin of the computational realm in social science disciplines such as psychology and sociology, natural sciences such as ecology and epistemology, and even areas in the humanities such as data journalism. These are fields where statistical models, scientific reproducibility, and data visualization are central concerns.

Perhaps it is best to think of R and Python not as two separate languages, but as two paths towards a goal of computational literacy. In this text, we'll be using the R route.

**Reproducible science**

The course will provide an introduction to some of the methods and tools of reproducible science. We will consider the replication crisis in the natural and social sciences, and then consider three distinct approaches which serve as partial solutions to the crisis. The first of these is training in a notebook-based approach to writing analyses, reports and projects (using R markdown documents). The second is using public repositories (such as the [Open Science Framework](https://osf.io/) and, to a limited extent, [GitHub](https://github.com/)) to provide snapshots of projects over time. Finally, the third is to consider the place of significance testing in the age of Big Data, and to provide training in the use of descriptive, exploratory techniques of data analysis.

**Principles and tools of data visualization**

As I note in the first chapter, communication is a distinguishing concern of data science for the liberal arts. "Communication" includes not just writing up results, but also designing data displays that incisively convey the key ideas or features in a flood of data. We'll examine and develop data visualizations such as plots, networks and text clouds. More advanced topics may include maps, interactive displays, and animations.

**Some data sets**

There are plenty of data sources for us to examine, and we'll consider existing datasets from disciplines ranging from literature to economics to public health, with sizes ranging from a few dozen to millions of data points. We will also clean and create new datasets.

## the changing nature of data science {.unnumbered}

One feature of Data Science is that it is changing rapidly. The tools, methods, data sources, and ethical concerns that face us today are different from those which shaped the field just a few years ago.

In fields that are undergoing rapid change, there is some trade-off between building expertise with existing (older) tools and trying the newer approaches. "Newer" is not always "better," but we want to equip you with skills that will not quickly become obsolete.

R is an open source system, which is contributed to by thousands of coders, and there are many approaches to study any given dataset or conceptual problem. These approaches are instantiated in over 24,000 different packages in the R system and will sometimes conflict with each other (for example, by using the same command in two contradictory ways).

In the last few years, we've shifted the class from a focus on 'Base R' (as KL learned it from the [Johns Hopkins-Coursera Data Science Specialization](https://www.coursera.org/specializations/jhu-data-science)) to the **Tidyverse**, which can be considered a specialized dialect of R. Tidyverse syntax is intuitive and clear. It encourages good habits in programming, and allows us to manipulate datasets more simply, and to visualize them more clearly. It also points us towards a curated set of packages for addressing many problems in data science.

R is our programming language, but RStudio is the platform (technically, an Integrated Development Environment or IDE) that we will use write, run, and publish our work. While R is open-source, RStudio is published by Posit, a for-profit company which has spun off a number of additional products such as Posit Cloud (for cloud-based collaboration) and Shiny (for interactive graphics). We are likely to come across both of these later in the term.

### intelligence and artificial intelligence (AI) {.unnumbered}

Today, the most dramatic changes to data science are associated with AI. It is difficult to predict the consequences of advances in AI for things like career selection: Some areas are likely to be impacted by AI more than others, but because AI is still in its infancy, we can only speculate.

But one way to approach this question is to begin by considering what constitutes (human) "intelligence." According to Sternberg [-@sternberg2018intelligence], intelligence can be thought of as having three components. One of these is **Analytical Intelligence**, which includes things like planning, reasoning, acquiring knowledge, and problem solving. A second is **Creative Intelligence**, which includes both the ability to deal with novel situations effectively, and the ability to "automatize" or efficiently execute familiar tasks. The third is **Practical or Contextual Intelligence**, which includes the ability to adapt to new environments.

AI engines or agents (or simply AIs) are, for now at least, effective at only some of these. They are better than humans at knowledge acquisition, logical reasoning and some kinds of problem solving. All of these are parts of Analytical Intelligence. They are also better than us at one part of Sternberg's Creative Intelligence: They excel at many types of automatized routines.

Beyond this, AIs struggle. My desktop AI (Microsoft Copilot 365 Version 19.2508.31121.0) tells me that the strengths of AI, understood in the context of Sternberg's theory, make it ideal for things like "Data Analysis, Financial modeling, Diagnostics, Scheduling and logistics, and Repetitive administrative tasks." The first and last of these are core parts of data science, but not the whole of it. AI struggles (again, according to Copilot), with "Leadership and strategic decision-making, Counseling, therapy, and social work, Cross-cultural negotiation, [and] Artistic innovation requiring deep emotional resonance." Careers that are likely to grow include creative professions (design, storytelling), human-centered roles (coaching, diplomacy), and also hybrid roles, that is, "Professionals who use AI tools to enhance their work (e.g., data-informed decision-makers)."

All of this should be taken with a grain of salt. Today's AI capabilities are quite limited compared to what they will be a year from now, and the AI that you and I might use on our desktops is, in all likelihood, a simple version of what is already available to large-scale users.

### vibe coding {.unnumbered}

Introductory data science is, in the age of AI, moving towards *vibe coding*, where the focus is much less on syntax and more on things like logical reasoning and so-called "data intuition," or the acquired sensitivity to data that don't make sense. The danger of vibe coding is that you literally don't know what you are doing, and that your code becomes a black box.

### how much should you use AI in this class? {.unnumbered}

Abraham Lincoln, who, at 6'4" (193 cm) was the tallest President in American history, was once asked how long a man's legs should be. Legend has it that he replied "long enough to reach the ground."

You should use AI just enough so that your legs reach the ground. AI should be your assistant in this class. It can help you, but not without extended dialogue and interaction. If you rely upon AI too much, you won't understand what you are doing, and you are likely to make some bizarre inferences. If you use AI too little, you are likely to get bogged down in syntax and make very little progress of substance. Learning how to use, and not to overuse, AI productively is an important skill. You will need to understand the gist of what your code is doing and why.

## exercises {.unnumbered}

**0.1** For computational literacy to be a virtuous pursuit, it should ultimately be in the service of human values such as *dignity, health, justice, meaningfulness, achievement, freedom, connection, love, happiness, prosperity,* and *sustainability*. Imagine that you wanted to collect data on whether people valued these things. How would you do it? What would you find?[^00-preface-2]

[^00-preface-2]: Answers to selected exercises are in the appendix.

**0.2** Imagine that your class was presented with a two question exam. The first question was "What is the next prime number after 1471?" The second question was "Who was the next Governor of Maryland after Spiro Agnew?" If the mean number correct was zero, could we say anything about the variance or standard deviation?

**0.3** What does a correlation of -1.2 suggest?

**0.4** What is the relevance of the Abe Lincoln anecdote to the discussion of AI and vibe coding?
