```{r setupstandsfor, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# what R stands for ...

R was initially developed by Ross Ihaka and Robert Gentleman as a tool to help teach university-level statistics at the University of Auckland in New Zealand. At one level, the name 'R' simply stands for the first initial of these two founders [@hornik2022]. But, just as the 'C' in Type C Data Analysis can be said to stand for concepts such as concentration, communication, collaboration, the 'R' in our programming language means much more:

R is a system for **reproducible** analysis, and reproducibility is essential. When we write R code, we'll use R markdown (and Quarto) documents.[^03-whatrstandsfor-1] These formats can include text (comments or explanations), 'chunks' of code, and output including graphs and tables, in a single place. Having explanations, code, and results in a single document facilitates reproducible work. (Jupyter notebooks in the Python world are similar in this respect).

[^03-whatrstandsfor-1]: The R markdown programming language is slowly being replaced with newer, and ultimately more capable, software called Quarto. Quarto is largely back-compatible with R markdown, but can be used with other languages including Python as well. A description of the differences between R markdown and Quarto may be found [here](https://quarto.org/docs/faq/rmarkdown.html). For our purposes, you can treat Quarto files (.qmd suffix) as R markdown files (.rmd), and vice-versa. Note that at this time, some Windows machines (including KL's) have difficulty rendering Quarto documents (Quarto rendering issue #14642).

R is for **research**. Research is not just an end-product, not just a published paper or book:

> ... these documents are not the research [rather] these documents are the "advertising". The research is the "full software environment, code, and data that produced the results" [@buckheit1995; @donoho2010, 385].

Published works (including theses as well as books, scholarly papers, and business reports) are summaries; R markdown documents are the raw materials from which these are derived. When we consider only summaries (or the 'advertising'), we make it difficult for others to verify, or build upon, the findings by reproducing them [@gandrud2013].

R is a system for **representing** data in cool, insight-facilitating ways, a tool for creating (reproducible) data visualizations which can provide insights and communicate results. The power of R to make clear, honest, and reproducible data visualizations is widely seen as a major strength of the language.

R can be considered to be '**received.'** In philosophy of science, the 'received view' refers to a standard way of thinking about evidence in scientific theories [@lutz2012]. Similarly, coding in R is sufficiently popular to be considered a 'standard' of sorts. Learning R could make you a more versatile and attractive candidate for many graduate programs as well as jobs in the private sector.

Because R is popular, there are many **resources**, including, for example -

> Online resources include the simple (and less simple) lessons of SwirlR, which offers the possibility of "learning R in R," as well as DataCamp, the Data Science Certificate Program at Johns Hopkins, and other MOOCs.
>
> Books include [@peng2014] - which includes not only videos of his lectures in the program at Hopkins, but also a brief list of still more resources - and [@wickham2023]

You'll also learn (more directly) from people, including your classmates, as well as the broader community of people around the world. There are hundreds if not thousands of people, young and old, who are on the road with you. I am as well, just a step or two (hopefully) ahead.

R might stand for **relatively high level**. Programming languages can be described along a continuum from high to low level, the former (like R) are more accessible to humans, the latter (like assembly language) more accessible to machines. Python, Java, and C++ are all more towards the middle of this continuum.

R does not stand for '[**arggh**](https://www.urbandictionary.com/define.php?term=ARGH),' although you may proclaim this in frustration ('arggh, why can't I get this to work?) or, perhaps, in satisfaction ('arggh, matey, that be a clever way of doing this').[^03-whatrstandsfor-2]

[^03-whatrstandsfor-2]: Actually, pirates have little use for R, because pirates love the C (programming language).

But R does stand for **rewarding**. If you are an experienced coder, you have felt the sense of accomplishment that follows from programming. If you are not experienced - even better. You have more to learn, and so will learn more, than your classmates in the time to come.

A language is a way of thinking about the world, and this is true for computer languages as well. You'll be challenged at times by its complexity, its obscurity, its seemingly alien logic. But you will succeed, and you will find that you can do things that you did not believe possible.

### base R and packages

R is a programming language. It can be seen as including two parts, a simple core (Base R) and a large number of additional packages. These packages (libraries) are customized add-ons which simplify certain tasks, such as text analysis. There are, at this writing, 24,309 available packages on the CRAN package repository (as well as additional useful packages that, for one reason or another, do not appear on CRAN). Packages on CRAN are partially indexed by "task view pages." The [task view page for natural language processing](https://cran.r-project.org/web/views/NaturalLanguageProcessing.html) or text analysis includes, at this writing, 60 separate packages.

So how do you choose, and where do you begin? For our purposes, we will start with the curated list of packages which jointly comprise the tidyverse [@wickham2019], which is effectively a dialect of R. You can learn more about the tidyverse and its place in data science in the [introduction to the Wickham text](https://r4ds.hadley.nz/intro.html)[@wickham2023].

To download the tidyverse package from the 'net, open RStudio, find the 'console' window on the left side of your screen, and enter the following command followed by \<enter\> or \<return\>

> install.packages("tidyverse")

## some technical characteristics

R is an object-oriented language - one conceptually organized around objects and data rather than actions and logic.

In R, at the most basic or atomic level, "objects" include characters, real numbers, integers, complex numbers, and logicals.

These atomic objects may be combined into vectors, which generally include objects of the same type [one kind of object, 'lists,' is an exception to this; @peng2014]. Vectors can be further combined into data frames, which are two-dimensional tables or arrays. A *tibble* is a particular type of data frame which is used in the tidyverse. Tibbles are, in some ways, handier to work with than other data frames. We'll be working extensively with data frames in general, and tibbles in particular, as we move forward.

Objects have attributes. Attributes of R include such things as name, dimensions (for vectors and arrays), class (that's the type of object described in the previous paragraph), length, etc.

Real world data sets are messy, and frequently have **missing values**. In R, missing values may be represented by NA (not available) or NaN (not a number, implying an undefined or impossible value).

## finding help

One does not simply 'learn R.' Unlike, say, learning to ride a bicycle, fry an egg, or drive a car with a manual transmission, learning R is not a discrete accomplishment that one can be said to have mastered and from which one then moves on. Rather, R is an evolving, open system of applications and tools which is so vast that there is always more that one can achieve, new lessons that one can learn. And, the complexity of R syntax is such that, for almost all of us, we will need help for coding on any non-trivial task.

For us, the key ideas in "looking for help" will include not just the tools on the RStudio IDE, but also (a) using Google searches wisely, (b) judicious use of AI assistance, and (c) reaching out to your classmates and instructor.

Finally, to get a sense of the power and versatility of R Markdown documents, you might explore this [tutorial](https://rmarkdown.rstudio.com/lesson-1.html). Note that, if you want to work interactively with the tutorial, you will need to first sign up for an account on RStudio cloud. Go to [posit.cloud](https://posit.cloud), click on "learn more" in the "Free" column, then sign up.

When you encounter obstacles, remember to maintain a balance between persistence and help-seeking.
