<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>21 working with text: a case study | 99-MoreExercises</title>
  <meta name="description" content="21 working with text: a case study | 99-MoreExercises" />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="21 working with text: a case study | 99-MoreExercises" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="kevinlanning/DSLA25" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="21 working with text: a case study | 99-MoreExercises" />
  
  
  

<meta name="author" content="Kevin Lanning" />


<meta name="date" content="2025-08-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"/>
<link rel="next" href="an-introduction-to-networks.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>preface</a>
<ul>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#the-role-of-the-liberal-arts-in-data-science"><i class="fa fa-check"></i>the role of the liberal arts in data science</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#some-features-of-the-text"><i class="fa fa-check"></i>some features of the text</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html#the-book-is-for-you"><i class="fa fa-check"></i>the book is for you</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-i-introduction.html"><a href="part-i-introduction.html"><i class="fa fa-check"></i>PART I: Introduction</a></li>
<li class="chapter" data-level="1" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html"><i class="fa fa-check"></i><b>1</b> what is “data science for the liberal arts?”</a>
<ul>
<li class="chapter" data-level="1.1" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html#the-incompleteness-of-the-data-science-venn-diagram"><i class="fa fa-check"></i><b>1.1</b> the incompleteness of the data science Venn diagram</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html#additional-domains"><i class="fa fa-check"></i><b>1.1.1</b> additional domains</a></li>
<li class="chapter" data-level="1.1.2" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html#an-additional-dimension"><i class="fa fa-check"></i><b>1.1.2</b> an additional dimension</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html#the-importance-of-data-science-for-society"><i class="fa fa-check"></i><b>1.2</b> the importance of data science for society</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html#intelligence-artificial-intelligence-ai-and-careers"><i class="fa fa-check"></i><b>1.2.1</b> intelligence, artificial intelligence (AI), and careers</a></li>
<li class="chapter" data-level="1.2.2" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html#the-challenge-of-tmi"><i class="fa fa-check"></i><b>1.2.2</b> the challenge of TMI</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="what-is-data-science-for-the-liberal-arts.html"><a href="what-is-data-science-for-the-liberal-arts.html#discussion-what-are-your-objectives-in-data-science"><i class="fa fa-check"></i><b>1.3</b> discussion: what are your objectives in data science?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>2</b> getting started</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started.html"><a href="getting-started.html#are-you-already-a-programmer-and-statistician"><i class="fa fa-check"></i><b>2.1</b> are you already a programmer and statistician?</a></li>
<li class="chapter" data-level="2.2" data-path="getting-started.html"><a href="getting-started.html#spreadsheets---some-best-practices"><i class="fa fa-check"></i><b>2.2</b> spreadsheets - some best practices</a></li>
<li class="chapter" data-level="2.3" data-path="getting-started.html"><a href="getting-started.html#setting-up-your-laptop-some-basic-tools"><i class="fa fa-check"></i><b>2.3</b> setting up your laptop: some basic tools</a></li>
<li class="chapter" data-level="2.4" data-path="getting-started.html"><a href="getting-started.html#a-modified-15-minute-rule"><i class="fa fa-check"></i><b>2.4</b> a (modified) 15-minute rule</a></li>
<li class="chapter" data-level="2.5" data-path="getting-started.html"><a href="getting-started.html#installing-r-and-rstudio-desktop"><i class="fa fa-check"></i><b>2.5</b> installing R and RStudio desktop</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="what-r-stands-for.html"><a href="what-r-stands-for.html"><i class="fa fa-check"></i><b>3</b> what R stands for …</a>
<ul>
<li class="chapter" data-level="3.0.1" data-path="what-r-stands-for.html"><a href="what-r-stands-for.html#base-r-and-packages"><i class="fa fa-check"></i><b>3.0.1</b> base R and packages</a></li>
<li class="chapter" data-level="3.1" data-path="what-r-stands-for.html"><a href="what-r-stands-for.html#cha-cha-cha-changes"><i class="fa fa-check"></i><b>3.1</b> cha-cha-cha-changes</a></li>
<li class="chapter" data-level="3.2" data-path="what-r-stands-for.html"><a href="what-r-stands-for.html#some-technical-characteristics"><i class="fa fa-check"></i><b>3.2</b> some technical characteristics</a></li>
<li class="chapter" data-level="3.3" data-path="what-r-stands-for.html"><a href="what-r-stands-for.html#finding-help"><i class="fa fa-check"></i><b>3.3</b> finding help</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exploring-r-world.html"><a href="exploring-r-world.html"><i class="fa fa-check"></i><b>4</b> exploring R world</a>
<ul>
<li class="chapter" data-level="4.1" data-path="exploring-r-world.html"><a href="exploring-r-world.html#go-to-the-movies"><i class="fa fa-check"></i><b>4.1</b> go to the movies</a></li>
<li class="chapter" data-level="4.2" data-path="exploring-r-world.html"><a href="exploring-r-world.html#go-into-the-clouds"><i class="fa fa-check"></i><b>4.2</b> go into the clouds</a></li>
<li class="chapter" data-level="4.3" data-path="exploring-r-world.html"><a href="exploring-r-world.html#open-the-box"><i class="fa fa-check"></i><b>4.3</b> open the box</a></li>
<li class="chapter" data-level="4.4" data-path="exploring-r-world.html"><a href="exploring-r-world.html#go-to-datacamp"><i class="fa fa-check"></i><b>4.4</b> go to (data)camp</a></li>
<li class="chapter" data-level="4.5" data-path="exploring-r-world.html"><a href="exploring-r-world.html#learn-to-knit"><i class="fa fa-check"></i><b>4.5</b> learn to knit</a></li>
<li class="chapter" data-level="4.6" data-path="exploring-r-world.html"><a href="exploring-r-world.html#read-parts-of-another-introductory-book"><i class="fa fa-check"></i><b>4.6</b> read (parts of) another introductory book</a></li>
<li class="chapter" data-level="4.7" data-path="exploring-r-world.html"><a href="exploring-r-world.html#older-approaches"><i class="fa fa-check"></i><b>4.7</b> older approaches</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="exploring-r-world.html"><a href="exploring-r-world.html#using-swirl"><i class="fa fa-check"></i><b>4.7.1</b> <strong>using Swirl</strong></a></li>
<li class="chapter" data-level="4.7.2" data-path="exploring-r-world.html"><a href="exploring-r-world.html#readingwatching-roger-pengs-text-andor-videos"><i class="fa fa-check"></i><b>4.7.2</b> reading/watching Roger Peng’s text and/or videos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii-towards-data-literacy.html"><a href="part-ii-towards-data-literacy.html"><i class="fa fa-check"></i>Part II: Towards data literacy</a></li>
<li class="chapter" data-level="5" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html"><i class="fa fa-check"></i><b>5</b> now draw the rest of the owl</a>
<ul>
<li class="chapter" data-level="5.1" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#time-for-hands-on-experience"><i class="fa fa-check"></i><b>5.1</b> time for hands-on experience</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#consider-loading-the-tidyverse"><i class="fa fa-check"></i><b>5.1.1</b> consider loading the tidyverse</a></li>
<li class="chapter" data-level="5.1.2" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#now-explore-the-babynames-package"><i class="fa fa-check"></i><b>5.1.2</b> now explore the babynames package</a></li>
<li class="chapter" data-level="5.1.3" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#or-the-ggplot2movies-package"><i class="fa fa-check"></i><b>5.1.3</b> or the (ggplot2)movies package</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="now-draw-the-rest-of-the-owl.html"><a href="now-draw-the-rest-of-the-owl.html#assignment"><i class="fa fa-check"></i><b>5.2</b> assignment</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="literate-programming.html"><a href="literate-programming.html"><i class="fa fa-check"></i><b>6</b> literate programming</a>
<ul>
<li class="chapter" data-level="6.1" data-path="literate-programming.html"><a href="literate-programming.html#projects-are-directories"><i class="fa fa-check"></i><b>6.1</b> projects are directories</a></li>
<li class="chapter" data-level="6.2" data-path="literate-programming.html"><a href="literate-programming.html#scripts-are-files-of-code"><i class="fa fa-check"></i><b>6.2</b> scripts are files of code</a></li>
<li class="chapter" data-level="6.3" data-path="literate-programming.html"><a href="literate-programming.html#r-markdown-quarto-documents-combine-scripts-with-comments-and-once-knit-results"><i class="fa fa-check"></i><b>6.3</b> R markdown / Quarto documents combine scripts with comments and (once knit) results</a></li>
<li class="chapter" data-level="6.4" data-path="literate-programming.html"><a href="literate-programming.html#some-elements-of-coding-style"><i class="fa fa-check"></i><b>6.4</b> some elements of coding style</a></li>
<li class="chapter" data-level="6.5" data-path="literate-programming.html"><a href="literate-programming.html#what-to-do-when-you-are-stuck"><i class="fa fa-check"></i><b>6.5</b> What to do when you are stuck</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html"><i class="fa fa-check"></i><b>7</b> principles of data visualization</a>
<ul>
<li class="chapter" data-level="7.1" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#some-opening-thoughts"><i class="fa fa-check"></i><b>7.1</b> some opening thoughts</a></li>
<li class="chapter" data-level="7.2" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#some-early-graphs"><i class="fa fa-check"></i><b>7.2</b> some early graphs</a></li>
<li class="chapter" data-level="7.3" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#tukey-and-eda"><i class="fa fa-check"></i><b>7.3</b> Tukey and EDA</a></li>
<li class="chapter" data-level="7.4" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#approaches-to-graphs"><i class="fa fa-check"></i><b>7.4</b> approaches to graphs</a></li>
<li class="chapter" data-level="7.5" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#tufte-first-principles"><i class="fa fa-check"></i><b>7.5</b> Tufte: first principles</a></li>
<li class="chapter" data-level="7.6" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#the-politics-of-data-visualization"><i class="fa fa-check"></i><b>7.6</b> the politics of data visualization</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#poor-design-leads-to-an-uninformed-or-misinformed-world"><i class="fa fa-check"></i><b>7.6.1</b> poor design leads to an uninformed or misinformed world</a></li>
<li class="chapter" data-level="7.6.2" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#poor-design-can-be-a-tool-to-deceive"><i class="fa fa-check"></i><b>7.6.2</b> poor design can be a tool to deceive</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#the-psychology-of-data-visualization"><i class="fa fa-check"></i><b>7.7</b> the psychology of data visualization</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#the-power-of-animation"><i class="fa fa-check"></i><b>7.7.1</b> the power of animation</a></li>
<li class="chapter" data-level="7.7.2" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#telling-the-truth-when-the-truth-is-unclear"><i class="fa fa-check"></i><b>7.7.2</b> telling the truth when the truth is unclear</a></li>
<li class="chapter" data-level="7.7.3" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#visualizing-uncertainty"><i class="fa fa-check"></i><b>7.7.3</b> visualizing uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#exercises"><i class="fa fa-check"></i><b>7.8</b> exercises</a>
<ul>
<li class="chapter" data-level="" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#smartphone-sales"><i class="fa fa-check"></i>Smartphone sales</a></li>
<li class="chapter" data-level="" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#stand-your-ground"><i class="fa fa-check"></i>Stand your ground</a></li>
<li class="chapter" data-level="" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#big-businesses"><i class="fa fa-check"></i>Big businesses</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#further-reading-and-resources"><i class="fa fa-check"></i><b>7.9</b> further reading and resources</a></li>
<li class="chapter" data-level="7.10" data-path="principles-of-data-visualization.html"><a href="principles-of-data-visualization.html#notes-for-next-revision"><i class="fa fa-check"></i><b>7.10</b> notes for next revision</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html"><i class="fa fa-check"></i><b>8</b> visualization in R with ggplot</a>
<ul>
<li class="chapter" data-level="8.1" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#a-picture-words-numbers"><i class="fa fa-check"></i><b>8.1</b> a picture &gt; (words, numbers)?</a></li>
<li class="chapter" data-level="8.2" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#read-wickhams-opening-chapter"><i class="fa fa-check"></i><b>8.2</b> Read Wickham’s opening chapter</a></li>
<li class="chapter" data-level="8.3" data-path="visualization-in-r-with-ggplot.html"><a href="visualization-in-r-with-ggplot.html#explore"><i class="fa fa-check"></i><b>8.3</b> explore</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html"><i class="fa fa-check"></i><b>9</b> on probability and statistics</a>
<ul>
<li class="chapter" data-level="9.1" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#on-probability"><i class="fa fa-check"></i><b>9.1</b> on probability</a></li>
<li class="chapter" data-level="9.2" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#the-rules-of-probability"><i class="fa fa-check"></i><b>9.2</b> the rules of probability</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#keeping-conditional-probabilities-straight"><i class="fa fa-check"></i><b>9.2.1</b> keeping conditional probabilities straight</a></li>
<li class="chapter" data-level="9.2.2" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#exercises-1"><i class="fa fa-check"></i><b>9.2.2</b> exercises</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#continuous-probability-distributions"><i class="fa fa-check"></i><b>9.3</b> continuous probability distributions</a></li>
<li class="chapter" data-level="9.4" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#dangerous-equations"><i class="fa fa-check"></i><b>9.4</b> dangerous equations</a></li>
<li class="chapter" data-level="9.5" data-path="on-probability-and-statistics.html"><a href="on-probability-and-statistics.html#notes-for-next-revision-1"><i class="fa fa-check"></i><b>9.5</b> notes for next revision</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html"><i class="fa fa-check"></i><b>10</b> reproducibility and the replication crisis</a>
<ul>
<li class="chapter" data-level="10.1" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#answers-to-the-reproducibility-crisis"><i class="fa fa-check"></i><b>10.1</b> answers to the reproducibility crisis</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#partial-answer-1-tweak-or-abandon-nhst"><i class="fa fa-check"></i><b>10.1.1</b> partial answer 1: Tweak or abandon NHST</a></li>
<li class="chapter" data-level="10.1.2" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#partial-answer-2-keep-a-log-of-every-step-of-every-analysis-in-r-markdown-or-jupyter-notebooks"><i class="fa fa-check"></i><b>10.1.2</b> partial answer 2: Keep a log of every step of every analysis in R markdown or Jupyter notebooks</a></li>
<li class="chapter" data-level="10.1.3" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#partial-answer-3-pre-registration-of-your-research"><i class="fa fa-check"></i><b>10.1.3</b> partial answer 3: Pre-registration of your research</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#further-readings"><i class="fa fa-check"></i><b>10.2</b> further readings</a></li>
<li class="chapter" data-level="10.3" data-path="reproducibility-and-the-replication-crisis.html"><a href="reproducibility-and-the-replication-crisis.html#notes-for-next-revision-2"><i class="fa fa-check"></i><b>10.3</b> notes for next revision</a></li>
</ul></li>
<li class="part"><span><b>I Part III Towards data proficiency</b></span></li>
<li class="chapter" data-level="11" data-path="wrangling-and-tidying.html"><a href="wrangling-and-tidying.html"><i class="fa fa-check"></i><b>11</b> wrangling and tidying</a>
<ul>
<li class="chapter" data-level="11.1" data-path="wrangling-and-tidying.html"><a href="wrangling-and-tidying.html#the-structure-of-the-tidyverse"><i class="fa fa-check"></i><b>11.1</b> the structure of the tidyverse</a></li>
<li class="chapter" data-level="11.2" data-path="wrangling-and-tidying.html"><a href="wrangling-and-tidying.html#where-should-we-eat"><i class="fa fa-check"></i><b>11.2</b> where should we eat?</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="wrangling-and-tidying.html"><a href="wrangling-and-tidying.html#tall-and-wide-formats"><i class="fa fa-check"></i><b>11.2.1</b> tall and wide formats</a></li>
<li class="chapter" data-level="11.2.2" data-path="wrangling-and-tidying.html"><a href="wrangling-and-tidying.html#exercises-2"><i class="fa fa-check"></i><b>11.2.2</b> exercises</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="wrangling-and-tidying.html"><a href="wrangling-and-tidying.html#more-on-tidy-coding"><i class="fa fa-check"></i><b>11.3</b> more on tidy coding</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html"><i class="fa fa-check"></i><b>12</b> finding, exploring, cleaning, and combining data</a>
<ul>
<li class="chapter" data-level="12.1" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#florida-educational-data"><i class="fa fa-check"></i><b>12.1</b> florida educational data</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#a-digression-slash-windows-and-the-world."><i class="fa fa-check"></i><b>12.1.1</b> a digression: Slash, Windows and the world.</a></li>
<li class="chapter" data-level="12.1.2" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#getting-data-from-our-machine-into-r"><i class="fa fa-check"></i><b>12.1.2</b> getting data from our machine into R</a></li>
<li class="chapter" data-level="12.1.3" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#which-ones-are-high-schools"><i class="fa fa-check"></i><b>12.1.3</b> which ones are “high schools”?</a></li>
<li class="chapter" data-level="12.1.4" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#can-we-compute-district-county-means-from-these-data"><i class="fa fa-check"></i><b>12.1.4</b> can we compute district (county) means from these data?</a></li>
<li class="chapter" data-level="12.1.5" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#estimating-school-enrollments"><i class="fa fa-check"></i><b>12.1.5</b> estimating school enrollments</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#combining-datasets"><i class="fa fa-check"></i><b>12.2</b> combining datasets</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#challenges-in-joining-datasets"><i class="fa fa-check"></i><b>12.2.1</b> challenges in joining datasets</a></li>
<li class="chapter" data-level="12.2.2" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#some-approaches-to-fixing-the-data"><i class="fa fa-check"></i><b>12.2.2</b> some approaches to fixing the data</a></li>
<li class="chapter" data-level="12.2.3" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#estimating-the-relationship-between-economic-disadvantage-and-graduation-rates"><i class="fa fa-check"></i><b>12.2.3</b> estimating the relationship between economic disadvantage and graduation rates</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="finding-exploring-cleaning-and-combining-data.html"><a href="finding-exploring-cleaning-and-combining-data.html#recap-on-joining-files"><i class="fa fa-check"></i><b>12.3</b> recap / on joining files</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="applied-data-science.html"><a href="applied-data-science.html"><i class="fa fa-check"></i><b>13</b> applied data science</a>
<ul>
<li class="chapter" data-level="13.1" data-path="applied-data-science.html"><a href="applied-data-science.html#public-health-and-covid"><i class="fa fa-check"></i><b>13.1</b> public health and covid</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="applied-data-science.html"><a href="applied-data-science.html#covid-data-in-2025"><i class="fa fa-check"></i><b>13.1.1</b> COVID data in 2025</a></li>
<li class="chapter" data-level="13.1.2" data-path="applied-data-science.html"><a href="applied-data-science.html#a-brief-digression-on-causality"><i class="fa fa-check"></i><b>13.1.2</b> a brief digression on causality</a></li>
<li class="chapter" data-level="13.1.3" data-path="applied-data-science.html"><a href="applied-data-science.html#the-excess-mortality-package"><i class="fa fa-check"></i><b>13.1.3</b> the excess mortality package</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="applied-data-science.html"><a href="applied-data-science.html#other-datasets-in-and-beyond-r"><i class="fa fa-check"></i><b>13.2</b> other datasets in and beyond R</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="applied-data-science.html"><a href="applied-data-science.html#makeextractcombine-your-own-data"><i class="fa fa-check"></i><b>13.2.1</b> make/extract/combine your own data</a></li>
<li class="chapter" data-level="13.2.2" data-path="applied-data-science.html"><a href="applied-data-science.html#keep-it-manageable"><i class="fa fa-check"></i><b>13.2.2</b> keep it manageable</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html"><i class="fa fa-check"></i><b>14</b> strings, factors, dates, and times</a>
<ul>
<li class="chapter" data-level="14.1" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#strings"><i class="fa fa-check"></i><b>14.1</b> strings</a></li>
<li class="chapter" data-level="14.2" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#factors"><i class="fa fa-check"></i><b>14.2</b> factors</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#types-of-babies"><i class="fa fa-check"></i><b>14.2.1</b> types of babies</a></li>
<li class="chapter" data-level="14.2.2" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#types-of-grown-ups"><i class="fa fa-check"></i><b>14.2.2</b> types of grown-ups</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#dates"><i class="fa fa-check"></i><b>14.3</b> dates</a></li>
<li class="chapter" data-level="14.4" data-path="strings-factors-dates-and-times.html"><a href="strings-factors-dates-and-times.html#times"><i class="fa fa-check"></i><b>14.4</b> times</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="lists.html"><a href="lists.html"><i class="fa fa-check"></i><b>15</b> lists</a></li>
<li class="chapter" data-level="16" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html"><i class="fa fa-check"></i><b>16</b> loops, functions, and beyond</a>
<ul>
<li class="chapter" data-level="16.1" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#loops"><i class="fa fa-check"></i><b>16.1</b> loops</a></li>
<li class="chapter" data-level="16.2" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#from-loop-to-apply-to-purrrmap"><i class="fa fa-check"></i><b>16.2</b> from loop to apply to purrr::map</a></li>
<li class="chapter" data-level="16.3" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#some-examples-of-functions"><i class="fa fa-check"></i><b>16.3</b> some examples of functions</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#preliminaries"><i class="fa fa-check"></i><b>16.3.1</b> preliminaries</a></li>
<li class="chapter" data-level="16.3.2" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#the-function"><i class="fa fa-check"></i><b>16.3.2</b> the function</a></li>
<li class="chapter" data-level="16.3.3" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#applying-the-function"><i class="fa fa-check"></i><b>16.3.3</b> applying the function</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="loops-functions-and-beyond.html"><a href="loops-functions-and-beyond.html#how-many-bottles-of-what"><i class="fa fa-check"></i><b>16.4</b> how many bottles of what?</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="from-correlation-to-multiple-regression.html"><a href="from-correlation-to-multiple-regression.html"><i class="fa fa-check"></i><b>17</b> from correlation to multiple regression</a>
<ul>
<li class="chapter" data-level="17.1" data-path="from-correlation-to-multiple-regression.html"><a href="from-correlation-to-multiple-regression.html#bivariate-analysis-galtons-height-data"><i class="fa fa-check"></i><b>17.1</b> bivariate analysis: Galton’s height data</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="from-correlation-to-multiple-regression.html"><a href="from-correlation-to-multiple-regression.html#correlations-based-on-small-samples-are-unstable-a-monte-carlo-demonstration"><i class="fa fa-check"></i><b>17.1.1</b> correlations based on small samples are unstable: A Monte Carlo demonstration</a></li>
<li class="chapter" data-level="17.1.2" data-path="from-correlation-to-multiple-regression.html"><a href="from-correlation-to-multiple-regression.html#from-correlation-to-regression"><i class="fa fa-check"></i><b>17.1.2</b> from correlation to regression</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="from-correlation-to-multiple-regression.html"><a href="from-correlation-to-multiple-regression.html#multivariate-data"><i class="fa fa-check"></i><b>17.2</b> multivariate data</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="cross-validation.html"><a href="cross-validation.html"><i class="fa fa-check"></i><b>18</b> cross-validation</a>
<ul>
<li class="chapter" data-level="18.1" data-path="cross-validation.html"><a href="cross-validation.html#revisiting-the-affairs-data"><i class="fa fa-check"></i><b>18.1</b> revisiting the affairs data</a></li>
<li class="chapter" data-level="18.2" data-path="cross-validation.html"><a href="cross-validation.html#avoiding-capitalizing-on-chance"><i class="fa fa-check"></i><b>18.2</b> avoiding capitalizing on chance</a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="cross-validation.html"><a href="cross-validation.html#splitting-the-data-into-training-and-test-subsamples"><i class="fa fa-check"></i><b>18.2.1</b> splitting the data into training and test subsamples</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="cross-validation.html"><a href="cross-validation.html#an-example-of-cross-validated-linear-regression"><i class="fa fa-check"></i><b>18.3</b> an example of cross-validated linear regression</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="cross-validation.html"><a href="cross-validation.html#applying-logistic-regression-analysis-to-the-training-data"><i class="fa fa-check"></i><b>18.3.1</b> applying logistic regression analysis to the training data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html"><i class="fa fa-check"></i><b>19</b> prediction and classification</a>
<ul>
<li class="chapter" data-level="19.1" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#from-regression-to-classification-selection-of-a-threshold"><i class="fa fa-check"></i><b>19.1</b> from regression to classification: selection of a threshold</a>
<ul>
<li class="chapter" data-level="19.1.1" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#applying-the-model-to-the-test-data"><i class="fa fa-check"></i><b>19.1.1</b> applying the model to the test data</a></li>
<li class="chapter" data-level="19.1.2" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#changing-our-decision-threshold"><i class="fa fa-check"></i><b>19.1.2</b> changing our decision threshold</a></li>
<li class="chapter" data-level="19.1.3" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#more-confusion"><i class="fa fa-check"></i><b>19.1.3</b> more confusion</a></li>
<li class="chapter" data-level="19.1.4" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#rocs-and-auc"><i class="fa fa-check"></i><b>19.1.4</b> ROCs and AUC</a></li>
</ul></li>
<li class="chapter" data-level="19.2" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#another-approach-to-classification-k-nearest-neighbor"><i class="fa fa-check"></i><b>19.2</b> another approach to classification: k-nearest neighbor</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#application-the-affairs-data"><i class="fa fa-check"></i><b>19.2.1</b> application: the affairs data</a></li>
<li class="chapter" data-level="19.2.2" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#from-one-doppelganger-to-many"><i class="fa fa-check"></i><b>19.2.2</b> from one doppelganger to many</a></li>
<li class="chapter" data-level="19.2.3" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#the-bayesian-classifier"><i class="fa fa-check"></i><b>19.2.3</b> the Bayesian classifier</a></li>
<li class="chapter" data-level="19.2.4" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#back-to-the-affairs-data"><i class="fa fa-check"></i><b>19.2.4</b> Back to the affairs data</a></li>
<li class="chapter" data-level="19.2.5" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#avoiding-capitalization-on-chance-again"><i class="fa fa-check"></i><b>19.2.5</b> avoiding capitalization on chance (again)</a></li>
<li class="chapter" data-level="19.2.6" data-path="prediction-and-classification.html"><a href="prediction-and-classification.html#the-multinomial-case"><i class="fa fa-check"></i><b>19.2.6</b> the multinomial case</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><i class="fa fa-check"></i><b>20</b> machine learning: chihuahuas vs muffins, and other distinctions and ideas</a>
<ul>
<li class="chapter" data-level="20.1" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#supervised-versus-unsupervised"><i class="fa fa-check"></i><b>20.1</b> supervised versus unsupervised</a></li>
<li class="chapter" data-level="20.2" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#prediction-versus-classification"><i class="fa fa-check"></i><b>20.2</b> prediction versus classification</a></li>
<li class="chapter" data-level="20.3" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#understanding-versus-prediction"><i class="fa fa-check"></i><b>20.3</b> understanding versus prediction</a></li>
<li class="chapter" data-level="20.4" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#bias-versus-variability"><i class="fa fa-check"></i><b>20.4</b> bias versus variability</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#resampling-beyond-test-training-and-validation-samples"><i class="fa fa-check"></i><b>20.4.1</b> resampling: beyond test, training, and validation samples</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#compensatory-versus-non-compensatory-problems"><i class="fa fa-check"></i><b>20.5</b> compensatory versus non-compensatory problems</a></li>
<li class="chapter" data-level="20.6" data-path="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html"><a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html#a-postscript-the-tidymodels-packages"><i class="fa fa-check"></i><b>20.6</b> a postscript: The Tidymodels packages</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html"><i class="fa fa-check"></i><b>21</b> working with text: a case study</a>
<ul>
<li class="chapter" data-level="21.1" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#federal-workers"><i class="fa fa-check"></i><b>21.1</b> federal workers</a></li>
<li class="chapter" data-level="21.2" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#finding-reddit-data"><i class="fa fa-check"></i><b>21.2</b> finding Reddit data</a></li>
<li class="chapter" data-level="21.3" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#some-initial-observations"><i class="fa fa-check"></i><b>21.3</b> some initial observations</a></li>
<li class="chapter" data-level="21.4" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#preprocessing"><i class="fa fa-check"></i><b>21.4</b> preprocessing</a></li>
<li class="chapter" data-level="21.5" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#comparing-the-words-and-stems"><i class="fa fa-check"></i><b>21.5</b> comparing the words and stems</a></li>
<li class="chapter" data-level="21.6" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#construction-of-differential-word-clouds"><i class="fa fa-check"></i><b>21.6</b> Construction of differential word clouds</a></li>
<li class="chapter" data-level="21.7" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#bigrams"><i class="fa fa-check"></i><b>21.7</b> bigrams</a></li>
<li class="chapter" data-level="21.8" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#categories-of-words"><i class="fa fa-check"></i><b>21.8</b> categories of words</a></li>
<li class="chapter" data-level="21.9" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#code-for-assessing-liwc-effect-sizes-between-2-groups"><i class="fa fa-check"></i><b>21.9</b> Code for assessing LIWC effect sizes between 2 groups</a></li>
<li class="chapter" data-level="21.10" data-path="working-with-text-a-case-study.html"><a href="working-with-text-a-case-study.html#exercise-what-would-you-do-next"><i class="fa fa-check"></i><b>21.10</b> exercise: what would you do next?</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="an-introduction-to-networks.html"><a href="an-introduction-to-networks.html"><i class="fa fa-check"></i><b>22</b> an introduction to networks</a>
<ul>
<li class="chapter" data-level="22.1" data-path="an-introduction-to-networks.html"><a href="an-introduction-to-networks.html#key-network-concepts"><i class="fa fa-check"></i><b>22.1</b> key network concepts</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="an-introduction-to-networks.html"><a href="an-introduction-to-networks.html#a-simple-example-networks-and-balance-theory"><i class="fa fa-check"></i><b>22.1.1</b> a simple example: networks and balance theory</a></li>
<li class="chapter" data-level="22.1.2" data-path="an-introduction-to-networks.html"><a href="an-introduction-to-networks.html#centrality"><i class="fa fa-check"></i><b>22.1.2</b> centrality</a></li>
<li class="chapter" data-level="22.1.3" data-path="an-introduction-to-networks.html"><a href="an-introduction-to-networks.html#components-and-communities"><i class="fa fa-check"></i><b>22.1.3</b> components and communities</a></li>
<li class="chapter" data-level="22.1.4" data-path="an-introduction-to-networks.html"><a href="an-introduction-to-networks.html#another-example-its-a-small-world"><i class="fa fa-check"></i><b>22.1.4</b> another example: it’s a small world</a></li>
<li class="chapter" data-level="22.1.5" data-path="an-introduction-to-networks.html"><a href="an-introduction-to-networks.html#static-and-dynamic-networks"><i class="fa fa-check"></i><b>22.1.5</b> static and dynamic networks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="case-study-the-network-structure-of-computational-social-science.html"><a href="case-study-the-network-structure-of-computational-social-science.html"><i class="fa fa-check"></i><b>23</b> case study: the network structure of computational social science</a>
<ul>
<li class="chapter" data-level="23.0.1" data-path="case-study-the-network-structure-of-computational-social-science.html"><a href="case-study-the-network-structure-of-computational-social-science.html#from-citation-network-to-structural-network"><i class="fa fa-check"></i><b>23.0.1</b> from citation network to structural network</a></li>
<li class="chapter" data-level="23.0.2" data-path="case-study-the-network-structure-of-computational-social-science.html"><a href="case-study-the-network-structure-of-computational-social-science.html#looking-at-the-whole-citation-network"><i class="fa fa-check"></i><b>23.0.2</b> looking at the whole citation network</a></li>
<li class="chapter" data-level="23.0.3" data-path="case-study-the-network-structure-of-computational-social-science.html"><a href="case-study-the-network-structure-of-computational-social-science.html#the-structural-network-centrality-and-community-structure"><i class="fa fa-check"></i><b>23.0.3</b> the structural network: Centrality and community structure</a></li>
<li class="chapter" data-level="23.0.4" data-path="case-study-the-network-structure-of-computational-social-science.html"><a href="case-study-the-network-structure-of-computational-social-science.html#visualizing-the-network"><i class="fa fa-check"></i><b>23.0.4</b> visualizing the network</a></li>
<li class="chapter" data-level="23.0.5" data-path="case-study-the-network-structure-of-computational-social-science.html"><a href="case-study-the-network-structure-of-computational-social-science.html#exploring-the-communities"><i class="fa fa-check"></i><b>23.0.5</b> exploring the communities</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html"><i class="fa fa-check"></i><b>24</b> some ethical concerns for the data scientist</a>
<ul>
<li class="chapter" data-level="24.1" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#ethics-and-personality-harvesting"><i class="fa fa-check"></i><b>24.1</b> ethics and personality harvesting</a></li>
<li class="chapter" data-level="24.2" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#the-law-of-unintended-consequences"><i class="fa fa-check"></i><b>24.2</b> the law of unintended consequences</a></li>
<li class="chapter" data-level="24.3" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#your-privacy-is-my-concern"><i class="fa fa-check"></i><b>24.3</b> your privacy is my concern</a></li>
<li class="chapter" data-level="24.4" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#who-should-hold-the-digital-keys"><i class="fa fa-check"></i><b>24.4</b> who should hold the digital keys?</a></li>
<li class="chapter" data-level="24.5" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#contact-tracing-and-covid-19"><i class="fa fa-check"></i><b>24.5</b> contact-tracing and COVID-19</a></li>
<li class="chapter" data-level="24.6" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#the-digital-divide"><i class="fa fa-check"></i><b>24.6</b> the digital divide</a></li>
<li class="chapter" data-level="24.7" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#still-more-case-studies"><i class="fa fa-check"></i><b>24.7</b> still more case studies</a></li>
<li class="chapter" data-level="24.8" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#some-potential-remedies"><i class="fa fa-check"></i><b>24.8</b> some potential remedies</a></li>
<li class="chapter" data-level="24.9" data-path="some-ethical-concerns-for-the-data-scientist.html"><a href="some-ethical-concerns-for-the-data-scientist.html#technology-change-and-risk"><i class="fa fa-check"></i><b>24.9</b> technology, change, and risk</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="exercises-3.html"><a href="exercises-3.html"><i class="fa fa-check"></i><b>25</b> exercises</a>
<ul>
<li class="chapter" data-level="25.1" data-path="exercises-3.html"><a href="exercises-3.html#generating-correlated-data-gpa-and-sat-and-putting-it-in-a-google-sheet"><i class="fa fa-check"></i><b>25.1</b> generating correlated data (GPA and SAT) and putting it in a Google Sheet</a></li>
<li class="chapter" data-level="25.2" data-path="exercises-3.html"><a href="exercises-3.html#now-look-at-your-data-in-the-spreadsheet"><i class="fa fa-check"></i><b>25.2</b> now look at your data in the spreadsheet</a></li>
<li class="chapter" data-level="25.3" data-path="exercises-3.html"><a href="exercises-3.html#using-ai-to-help-us-here"><i class="fa fa-check"></i><b>25.3</b> using AI to help us here</a>
<ul>
<li class="chapter" data-level="25.3.1" data-path="exercises-3.html"><a href="exercises-3.html#for-last-names-its-a-little-bit-trickier"><i class="fa fa-check"></i><b>25.3.1</b> for last names, it’s a little bit trickier</a></li>
<li class="chapter" data-level="25.3.2" data-path="exercises-3.html"><a href="exercises-3.html#cleaning-these-up"><i class="fa fa-check"></i><b>25.3.2</b> cleaning these up</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="exercises-3.html"><a href="exercises-3.html#getting-data-from-a-package-like-mdsr"><i class="fa fa-check"></i><b>25.4</b> Getting data from a package like MDSR</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">99-MoreExercises</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="working-with-text-a-case-study" class="section level1 hasAnchor" number="21">
<h1><span class="header-section-number">21</span> working with text: a case study<a href="working-with-text-a-case-study.html#working-with-text-a-case-study" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, I present a rudimentary case study in which a contemporary issue is explored using R. I examine Reddit<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a> data, create comparison word-clouds from single words and two-word strings (bigrams), and consider the results of an external proprietary tool for examining categories of language. The chapter is based on the tidy approach to text analysis, for which a clear and thorough introduction has been provided in two books by Silge and her colleagues, each of which is available online
<span class="citation">Hvitfeldt and Silge (<a href="#ref-hvitfeldt2021">2021</a>)</span>.</p>
<p>A word of warning: This chapter is light on the grunt work of data wrangling and preprocessing, which were introduced in Chapter 14. Keep in mind that that work is typically very time-consuming.</p>
<div id="federal-workers" class="section level2 hasAnchor" number="21.1">
<h2><span class="header-section-number">21.1</span> federal workers<a href="working-with-text-a-case-study.html#federal-workers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>On March 19, 2025, the <em>New York Times</em> ran an article with the title “<a href="https://www.nytimes.com/2025/03/19/technology/reddit-va-federal-workers.html?unlocked_article_code=1.6k4.hnKX.dQvNDEhfhgcl&amp;smid=url-share"><em>Will I Lose My Job?’ Federal Workers Flock to Reddit for Answers</em></a><em>.”</em> The gist of the article was that US Federal workers, facing job insecurity in the opening days of President Trump’s second term, were using the <em>r/fedworkers</em> subreddit to connect with others and communicate their anxieties, concerns, and strategies.</p>
<p>But did they, though? Is there evidence that the r/<em>fedworkers</em> subreddit was being used in these ways? In the analysis that follows, I will examine posts<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> to the community for the period from January 1, 2024 through March 24, 2025.</p>
<p>We’ll consider the following:</p>
<ul>
<li><p>What specific words differentiate Trump era posts (since his second inauguration in January 2025) from those from the Biden era (prior to the November 2024 election)? For this, we’ll rely primarily on visualizations, in particular, differential word clouds of single words and bigrams.</p></li>
<li><p>What categories of speech differentiate the two epochs? For this, we’ll use a proprietary tool, <em>Linguistic Inquiry and Word Count.</em> LIWC is a widely used measure for extracting grammatical, social, and psychological variables from text [LIWC; <span class="citation">Ryan L. Boyd et al. (<a href="#ref-boyd2022">2022</a>)</span>]. We’ll generate tables for the LIWC categories and examine the effect size and statistical significance of these differences.</p></li>
</ul>
<p>This approach can optionally be extended to additional comparisons, including:</p>
<ul>
<li><p>Are similar results obtained when we examine comments rather than posts? (Here, we could compare Trump-era words and categories with Biden-era words and categories).</p></li>
<li><p>How are comments and posts different from each other? (Here, we could compare words and categories for r/fedworkers posts with words and categories for r/fedworkers comments)</p></li>
<li><p>Does the content of posts (or comments) between the election and the inaugural more closely resemble that of the Biden era (as Biden was still president) or the coming Trump administration?</p></li>
</ul>
<p>In order to address these questions, we’ll briefly touch on some auxiliary technical questions as well, including:</p>
<ul>
<li><p>Should we ‘stem’ words prior to analysis? That is, should we treat terms such as (<em>donut</em> and <em>donuts</em>) as the same word or as different? How about (<em>go</em> and <em>going</em>)?</p></li>
<li><p>A similar question can be asked about case - should all characters be set to lowercase? That is, should (<em>I’m</em> and <em>i’m</em>) be treated as the same? How about (<em>DOGE</em> and <em>doge</em>)?</p></li>
<li><p>Should we include common stop words (<em>a</em>, <em>and</em>, <em>if</em>, <em>or</em>, <em>me</em>) in our analysis, or disregard them?</p></li>
</ul>
</div>
<div id="finding-reddit-data" class="section level2 hasAnchor" number="21.2">
<h2><span class="header-section-number">21.2</span> finding Reddit data<a href="working-with-text-a-case-study.html#finding-reddit-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Although Reddit data became less accessible beginning in 2023, archives of Reddit posts and comments remain readily available following some simple Web sleuthing. In this block, I begin with a set of posts that I have already downloaded.</p>
<p>We initially look at a very small set of data - 100 lines - both to make sure the code works and, if it does, to make an initial determination about what fields are of interest. The file is large, so it will ultimately be read in through streaming rather than all-at-once, hence the readLines -&gt; stream_in syntax.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="working-with-text-a-case-study.html#cb229-1" tabindex="-1"></a>posts <span class="ot">&lt;-</span> <span class="fu">read_lines</span>(<span class="st">&quot;data/r_fednews_posts.jsonl&quot;</span>, <span class="at">n_max =</span> <span class="dv">100</span>)</span>
<span id="cb229-2"><a href="working-with-text-a-case-study.html#cb229-2" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="fu">stream_in</span>(<span class="fu">textConnection</span>(</span>
<span id="cb229-3"><a href="working-with-text-a-case-study.html#cb229-3" tabindex="-1"></a>     <span class="fu">gsub</span>(<span class="st">&quot;</span><span class="sc">\\</span><span class="st">n&quot;</span>,<span class="st">&quot;&quot;</span>, posts))) </span></code></pre></div>
<pre><code>##  Found 100 records... Imported 100 records. Simplifying...</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="working-with-text-a-case-study.html#cb231-1" tabindex="-1"></a><span class="fu">glimpse</span>(a1)</span></code></pre></div>
<pre><code>## Rows: 100
## Columns: 113
## $ `_meta`                       &lt;df[,1]&gt; &lt;data.frame[26 x 1]&gt;
## $ all_awardings                 &lt;list&gt; [], [], [], [], [], [], [], [], [], […
## $ allow_live_comments           &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
## $ approved_at_utc               &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ approved_by                   &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ archived                      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ author                        &lt;chr&gt; &quot;Unlikely_Story1424&quot;, &quot;lakepirate1775&quot;, …
## $ author_flair_background_color &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ author_flair_css_class        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ author_flair_richtext         &lt;list&gt; [], [], [], [], [], [], [], [], [], [], …
## $ author_flair_template_id      &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
## $ author_flair_text             &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ author_flair_text_color       &lt;chr&gt; NA, NA, NA, NA, &quot;dark&quot;, NA, NA, NA, NA, …
## $ author_flair_type             &lt;chr&gt; &quot;text&quot;, &quot;text&quot;, &quot;text&quot;, &quot;text&quot;, &quot;text&quot;, …
## $ author_fullname               &lt;chr&gt; &quot;t2_dvmjwod3g&quot;, &quot;t2_3z3p2fng&quot;, &quot;t2_r0erp…
## $ author_is_blocked             &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ author_patreon_flair          &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ author_premium                &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ awarders                      &lt;list&gt; [], [], [], [], [], [], [], [], [], [], …
## $ banned_at_utc                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
## $ banned_by                     &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ can_gild                      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ can_mod_post                  &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ category                      &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ clicked                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ content_categories            &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ contest_mode                  &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ created                       &lt;int&gt; 1704074487, 1704075982, 1704083189, 1704…
## $ created_utc                   &lt;int&gt; 1704074487, 1704075982, 1704083189, 1704…
## $ discussion_type               &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ distinguished                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ domain                        &lt;chr&gt; &quot;self.fednews&quot;, &quot;self.fednews&quot;, &quot;self.fe…
## $ downs                         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ edited                        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ gilded                        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ gildings                      &lt;df[,0]&gt; &lt;data.frame[26 x 0]&gt;
## $ hidden                        &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ hide_score                    &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, T…
## $ id                            &lt;chr&gt; &quot;18vmmmu&quot;, &quot;18vn1fo&quot;, &quot;18vox52&quot;, &quot;18voyk…
## $ is_created_from_ads_ui        &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ is_crosspostable              &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, …
## $ is_meta                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ is_original_content           &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ is_reddit_media_domain        &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ is_robot_indexable            &lt;lgl&gt; FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, …
## $ is_self                       &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
## $ is_video                      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ likes                         &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ link_flair_background_color   &lt;chr&gt; &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, &quot;&quot;, NA, &quot;&quot;, &quot;&quot;, …
## $ link_flair_css_class          &lt;chr&gt; NA, NA, &quot;e&quot;, NA, &quot;c&quot;, &quot;c&quot;, NA, &quot;c&quot;, NA, …
## $ link_flair_richtext           &lt;list&gt; [&lt;data.frame[0 x 0]&gt;], [&lt;data.frame[0 x …
## $ link_flair_text               &lt;chr&gt; NA, NA, &quot;Misc&quot;, NA, &quot;Pay &amp; Benefits&quot;, &quot;P…
## $ link_flair_text_color         &lt;chr&gt; &quot;dark&quot;, &quot;dark&quot;, &quot;dark&quot;, &quot;dark&quot;, &quot;dark&quot;,…
## $ link_flair_type               &lt;chr&gt; &quot;text&quot;, &quot;text&quot;, &quot;richtext&quot;, &quot;text&quot;, &quot;ric…
## $ locked                        &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ media                         &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ media_embed                   &lt;df[,0]&gt; &lt;data.frame[26 x 0]&gt;
## $ media_only                    &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ mod_note                      &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ mod_reason_by                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ mod_reason_title              &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ mod_reports                   &lt;list&gt; [], [], [], [], [], [], [], [], [], [], …
## $ name                          &lt;chr&gt; &quot;t3_18vmmmu&quot;, &quot;t3_18vn1fo&quot;, &quot;t3_18vox52&quot;…
## $ no_follow                     &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
## $ num_comments                  &lt;int&gt; 1, 15, 1, 1, 1, 19, 1, 61, 220, 95, 1, …
## $ num_crossposts                &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ num_reports                   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ over_18                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ parent_whitelist_status       &lt;chr&gt; &quot;all_ads&quot;, &quot;all_ads&quot;, &quot;all_ads&quot;, &quot;all_ad…
## $ permalink                     &lt;chr&gt; &quot;/r/fednews/comments/18vmmmu/historical_…
## $ pinned                        &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ previous_selftext             &lt;chr&gt; &quot;[removed]&quot;, NA, NA, NA, NA, NA, NA, NA,…
## $ pwls                          &lt;int&gt; 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6…
## $ quarantine                    &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ removal_reason                &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ removed_by                    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ removed_by_category           &lt;chr&gt; &quot;automod_filtered&quot;, NA, &quot;moderator&quot;, &quot;mo…
## $ report_reasons                &lt;list&gt; [], [], [], [], [], [], [], [], [], [], …
## $ retrieved_on                  &lt;int&gt; 1704074505, 1704075998, 1704083206, 1704…
## $ saved                         &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ score                         &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 19, 1, 1, 1, 1, 1,…
## $ secure_media                  &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ secure_media_embed            &lt;df[,0]&gt; &lt;data.frame[26 x 0]&gt;
## $ selftext                      &lt;chr&gt; &quot;Anyone else here use Mint to track thei…
## $ send_replies                  &lt;lgl&gt; TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE…
## $ spoiler                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ stickied                      &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FA…
## $ subreddit                     &lt;chr&gt; &quot;fednews&quot;, &quot;fednews&quot;, &quot;fednews&quot;, &quot;fednew…
## $ subreddit_id                  &lt;chr&gt; &quot;t5_2xy8z&quot;, &quot;t5_2xy8z&quot;, &quot;t5_2xy8z&quot;, &quot;t5_…
## $ subreddit_name_prefixed       &lt;chr&gt; &quot;r/fednews&quot;, &quot;r/fednews&quot;, &quot;r/fednews&quot;, &quot;…
## $ subreddit_subscribers         &lt;int&gt; 72988, 72990, 73009, 73010, 73027, 73027…
## $ subreddit_type                &lt;chr&gt; &quot;public&quot;, &quot;public&quot;, &quot;public&quot;, &quot;public&quot;, …
## $ suggested_sort                &lt;chr&gt; &quot;confidence&quot;, &quot;confidence&quot;, &quot;confidence&quot;…
## $ thumbnail                     &lt;chr&gt; &quot;self&quot;, &quot;self&quot;, &quot;self&quot;, &quot;self&quot;, &quot;self&quot;, …
## $ thumbnail_height              &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ thumbnail_width               &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ title                         &lt;chr&gt; &quot;Historical TSP Data + Mint Shutdown&quot;, &quot;…
## $ top_awarded_type              &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ total_awards_received         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ treatment_tags                &lt;list&gt; [], [], [], [], [], [], [], [], [], [], …
## $ ups                           &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 19, 1, 1, 1, 1, 1, …
## $ upvote_ratio                  &lt;dbl&gt; 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00…
## $ url                           &lt;chr&gt; &quot;https://www.reddit.com/r/fednews/commen…
## $ user_reports                  &lt;list&gt; [], [], [], [], [], [], [], [], [], [],…
## $ view_count                    &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ visited                       &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…
## $ whitelist_status              &lt;chr&gt; &quot;all_ads&quot;, &quot;all_ads&quot;, &quot;all_ads&quot;, &quot;all_ad…
## $ wls                           &lt;int&gt; 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, …
## $ link_flair_template_id        &lt;chr&gt; NA, NA, &quot;998fe156-1729-11e4-9ea3-12313b0…
## $ media_metadata                &lt;df[,1]&gt; &lt;data.frame[26 x 1]&gt;
## $ post_hint                     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
## $ preview                       &lt;df[,2]&gt; &lt;data.frame[26 x 2]&gt;
## $ url_overridden_by_dest        &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …</code></pre>
<p>Only a few columns are of interest to us. We select those columns in the next chunk, for a sample of 10000 posts. We also take note of how long it takes to read a sample of this size by noting start-time, end.time, and the difference between these. Finally we make the date-time field (created_utc) field “human readable.”</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="working-with-text-a-case-study.html#cb233-1" tabindex="-1"></a>posts <span class="ot">&lt;-</span> <span class="fu">read_lines</span>(<span class="st">&quot;data/r_fednews_posts.jsonl&quot;</span>, <span class="at">n_max =</span> <span class="dv">10000</span>)</span>
<span id="cb233-2"><a href="working-with-text-a-case-study.html#cb233-2" tabindex="-1"></a>start.time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb233-3"><a href="working-with-text-a-case-study.html#cb233-3" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="fu">stream_in</span>(<span class="fu">textConnection</span>(</span>
<span id="cb233-4"><a href="working-with-text-a-case-study.html#cb233-4" tabindex="-1"></a>     <span class="fu">gsub</span>(<span class="st">&quot;</span><span class="sc">\\</span><span class="st">n&quot;</span>,<span class="st">&quot;&quot;</span>, posts))) <span class="sc">|&gt;</span> </span>
<span id="cb233-5"><a href="working-with-text-a-case-study.html#cb233-5" tabindex="-1"></a>     <span class="fu">select</span>(author, title, selftext, id, link_flair_text,</span>
<span id="cb233-6"><a href="working-with-text-a-case-study.html#cb233-6" tabindex="-1"></a>            num_comments, ups, downs, subreddit, created_utc) <span class="sc">|&gt;</span> </span>
<span id="cb233-7"><a href="working-with-text-a-case-study.html#cb233-7" tabindex="-1"></a>     <span class="fu">mutate</span> (<span class="at">date =</span> (<span class="fu">as_datetime</span>(created_utc))) <span class="sc">|&gt;</span> </span>
<span id="cb233-8"><a href="working-with-text-a-case-study.html#cb233-8" tabindex="-1"></a>     <span class="fu">select</span>(<span class="sc">-</span>created_utc)</span></code></pre></div>
<pre><code>##  Found 500 records... Found 1000 records... Found 1500 records... Found 2000 records... Found 2500 records... Found 3000 records... Found 3500 records... Found 4000 records... Found 4500 records... Found 5000 records... Found 5500 records... Found 6000 records... Found 6500 records... Found 7000 records... Found 7500 records... Found 8000 records... Found 8500 records... Found 9000 records... Found 9500 records... Found 10000 records... Imported 10000 records. Simplifying...</code></pre>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="working-with-text-a-case-study.html#cb235-1" tabindex="-1"></a>end.time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb235-2"><a href="working-with-text-a-case-study.html#cb235-2" tabindex="-1"></a>(end.time <span class="sc">-</span> start.time)</span></code></pre></div>
<pre><code>## Time difference of 7.90551 secs</code></pre>
<p>Looks good - the date/time field is clean, the columns are those that we want, and it only took a few seconds to read in 10,000 posts. Let’s read them all in, then take a look at a small random sample - 10 - of the texts of the posts.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="working-with-text-a-case-study.html#cb237-1" tabindex="-1"></a>posts <span class="ot">&lt;-</span> <span class="fu">read_lines</span>(<span class="st">&quot;data/r_fednews_posts.jsonl&quot;</span>)</span>
<span id="cb237-2"><a href="working-with-text-a-case-study.html#cb237-2" tabindex="-1"></a>start.time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb237-3"><a href="working-with-text-a-case-study.html#cb237-3" tabindex="-1"></a>a1 <span class="ot">&lt;-</span> <span class="fu">stream_in</span>(<span class="fu">textConnection</span>(</span>
<span id="cb237-4"><a href="working-with-text-a-case-study.html#cb237-4" tabindex="-1"></a>     <span class="fu">gsub</span>(<span class="st">&quot;</span><span class="sc">\\</span><span class="st">n&quot;</span>,<span class="st">&quot;&quot;</span>, posts))) <span class="sc">|&gt;</span> </span>
<span id="cb237-5"><a href="working-with-text-a-case-study.html#cb237-5" tabindex="-1"></a>     <span class="fu">select</span>(author, title, selftext, id, link_flair_text,</span>
<span id="cb237-6"><a href="working-with-text-a-case-study.html#cb237-6" tabindex="-1"></a>            num_comments, score, subreddit, created_utc) <span class="sc">|&gt;</span> </span>
<span id="cb237-7"><a href="working-with-text-a-case-study.html#cb237-7" tabindex="-1"></a>     <span class="fu">mutate</span> (<span class="at">date =</span> (<span class="fu">as_datetime</span>(created_utc))) <span class="sc">|&gt;</span> </span>
<span id="cb237-8"><a href="working-with-text-a-case-study.html#cb237-8" tabindex="-1"></a>     <span class="fu">select</span>(<span class="sc">-</span>created_utc)</span></code></pre></div>
<pre><code>##  Found 500 records... Found 1000 records... Found 1500 records... Found 2000 records... Found 2500 records... Found 3000 records... Found 3500 records... Found 4000 records... Found 4500 records... Found 5000 records... Found 5500 records... Found 6000 records... Found 6500 records... Found 7000 records... Found 7500 records... Found 8000 records... Found 8500 records... Found 9000 records... Found 9500 records... Found 10000 records... Found 10500 records... Found 11000 records... Found 11500 records... Found 12000 records... Found 12500 records... Found 13000 records... Found 13500 records... Found 14000 records... Found 14500 records... Found 15000 records... Found 15500 records... Found 16000 records... Found 16500 records... Found 17000 records... Found 17500 records... Found 18000 records... Found 18500 records... Found 19000 records... Found 19500 records... Found 20000 records... Found 20500 records... Found 21000 records... Found 21500 records... Found 22000 records... Found 22500 records... Found 23000 records... Found 23500 records... Found 24000 records... Found 24500 records... Found 25000 records... Found 25500 records... Found 26000 records... Found 26500 records... Found 27000 records... Found 27500 records... Found 28000 records... Found 28500 records... Found 29000 records... Found 29500 records... Found 30000 records... Found 30500 records... Found 31000 records... Found 31500 records... Found 32000 records... Found 32500 records... Found 33000 records... Found 33500 records... Found 34000 records... Found 34500 records... Found 35000 records... Found 35500 records... Found 36000 records... Found 36500 records... Found 37000 records... Found 37500 records... Found 38000 records... Found 38500 records... Found 39000 records... Found 39500 records... Found 40000 records... Found 40500 records... Found 41000 records... Found 41500 records... Found 42000 records... Found 42500 records... Found 43000 records... Found 43500 records... Found 44000 records... Found 44500 records... Found 45000 records... Found 45500 records... Found 46000 records... Found 46500 records... Found 47000 records... Found 47500 records... Found 48000 records... Found 48500 records... Found 49000 records... Found 49500 records... Found 50000 records... Found 50500 records... Found 51000 records... Found 51500 records... Found 52000 records... Found 52500 records... Found 53000 records... Found 53500 records... Found 54000 records... Found 54500 records... Found 55000 records... Found 55500 records... Found 56000 records... Found 56500 records... Found 57000 records... Found 57500 records... Found 58000 records... Found 58500 records... Found 59000 records... Found 59500 records... Found 59651 records... Imported 59651 records. Simplifying...</code></pre>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="working-with-text-a-case-study.html#cb239-1" tabindex="-1"></a>end.time <span class="ot">&lt;-</span> <span class="fu">Sys.time</span>()</span>
<span id="cb239-2"><a href="working-with-text-a-case-study.html#cb239-2" tabindex="-1"></a>(end.time <span class="sc">-</span> start.time)</span></code></pre></div>
<pre><code>## Time difference of 2.655577 mins</code></pre>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="working-with-text-a-case-study.html#cb241-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">33458</span>)</span>
<span id="cb241-2"><a href="working-with-text-a-case-study.html#cb241-2" tabindex="-1"></a>a1 <span class="sc">|&gt;</span> <span class="fu">select</span> (selftext) <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>##                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          selftext
## 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ACA and IRA provided alternate funding sources for several agencies to hire new FTEs. In my agency even when there was a hiring freeze from the general “congress appropriations” hiring budget, we were allowed to bring new people on through the IRA as direct hires. The ACA is also very contentious. If those laws get repealed what happens to those employees? 
## 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [removed]
## 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [removed]
## 4  I am a supervisor in USDA, more specifically FPAC. I have asked the higher ups for HR guidance on a problem employee (this has gone on for 3-4 years) and have received none. I have sent in numerous emails, detailing running records - the only documentation they have or considered doing anything on said employee was 3 years ago when she assaulted another employee. \n\nI have become excellent writing running records, I’ve learned valuable leadership and management skills when they said “maybe I am the one who needed to change.” They continue to fail to take any action. I asked for training on issues that pop up with her and nothing. I felt like I was crazy but visiting with EAP helped, the therapist was able to spot her out and personality quickly. I felt relieved. I try to stay positive but she brings down the whole office. She started bullying the other employees in another department (we’re open concept so they sit near each other) and I’m fed up. \n\nCan anyone point me to specific policies/ procedures from FPAC that I can utilize to track her performance and conduct? \nYes, I keep detailed running records but I don’t know what “counts” that can be written up. \n\n*Please note* I am not looking for things to write her up on, employee goes through “cycles” her mood in the office is like a roller coaster, and after working with her for 4 years and 5 years of managing her, I can predict with precision what she will do next. So this outburst she had with the other employees is just the start of what’s to come. 
## 5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [removed]
## 6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
## 7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         If the Supreme Court overturns Humphrey’s Executor, would all civil service protections be at risk?  I understand that principal officers would no longer be protected from presidential whims, but what about the rank and file?  Would the overturning of Humphrey’s Executor mean that the Pendleton Act and all subsequent civil service protections are unconstitutional and void?
## 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Other than sharing how we lost our jobs because of the illegal firings, what should we demand them to do? Argue that we should have a government shutdown next month? What emergency countermeasures, if any, do Democrats have right now that they can use?
## 9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [removed]
## 10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 We are NTEU 335, the union representing 1,100 CFPB employees, and we will be rallying at HQ today to protest the attack on the CFPB and its workers, who were locked out of their offices over the weekend. Please join us!\n\nWhere: CFPB Headquarters, 1700 G St NW, Washington DC 20552\n\nWhen: 4:15 pm, TODAY, February 10\n\nWho: YOU!!!</code></pre>
<p>These 59651 posts include all of those which were available for the period from January 1, 2024 through March 24, 2025.</p>
</div>
<div id="some-initial-observations" class="section level2 hasAnchor" number="21.3">
<h2><span class="header-section-number">21.3</span> some initial observations<a href="working-with-text-a-case-study.html#some-initial-observations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are a few interesting properties of the data:</p>
<ol style="list-style-type: decimal">
<li><p>One is that it appears that many of the posts have been removed, including 4 out of this (very small) sample of 10. It would be interesting to compare the proportion of deleted posts to this subreddit with those of other subreddits during the same period. (I would anticipate that this proportion is much higher in this subreddit, likely because of fears of retribution that may or may not be warranted). We should keep in mind that the removed or deleted posts are unlikely to be a random sample of posts on the subreddit - they may be more angry, more polarized, and/or more easily de-anonymized. We should return to this when we consider our results. For now, we will filter out the removed posts.</p>
<ol style="list-style-type: lower-alpha">
<li><em>One way to examine this empirically would be to examine the ‘titles’ field. The removed posts still include titles, so the nature of the removed posts in comparison with the non-removed posts could be examined by using the “compare words and categories” approach on the title fields of the two sets.</em></li>
</ol></li>
</ol>
<p>The second is that there are, at least in this small sample, a lot of abbreviations and acronyms - including <em>ACA</em>, <em>IRA</em>, <em>USDA</em>, <em>FPAC</em>, <em>NTEU</em>, <em>CFPB</em>, <em>HQ</em>, and <em>EAP</em>. Often, at this point in an analysis of text, we would reformat the text so that all words were lowercase (with the <em>tolower</em>) function. We’ll instead modify this a bit - retaining capitalization when a token is in ALL CAPS (and is more than a single character like “I” or “A”) - and making into lowercase otherwise.</p>
</div>
<div id="preprocessing" class="section level2 hasAnchor" number="21.4">
<h2><span class="header-section-number">21.4</span> preprocessing<a href="working-with-text-a-case-study.html#preprocessing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this next chunk, we create a new variable called ‘epoch,’ with three values, <em>Biden</em> (during the Biden presidency, but before the November election, <em>Lameduck</em> (the period between the election and Trump’s second inauguration), and <em>Trump</em>. We treat the ‘lameduck’ period separately because, although Biden was President, Trump, and concerns about the coming Trump presidency, was dominant on the airwaves. In these initial comparisons, we’ll exclude that lameduck period from analysis</p>
<p>We also take the content of the posts and unravel them, with one line per word (so that a post which had 100 words would be 100 lines in the new, tidy datafile). Call this file tidyCorpus0 (a <em>corpus</em> is a body of text).</p>
<p>We then selectively set the text to lowercase (retaining uppercase only when a multi-character token, or word, is in ALL CAPS). This gives us tidyCorpus1.</p>
<p>We also remove stopwords from the text in order to simplify and shorten the texts; acknowledging that there are often good reasons not to do this <span class="citation">Pennebaker et al. (<a href="#ref-pennebaker2014">2014</a>)</span>. We’ll remove numbers from the text in the same step. Call this file tidyCorpus2.</p>
<p>Finally, we stem the text, reducing each word to its common stem, using the SnowballC library. This gives is tidyCorpus3. If we were to stem the text, we would move ahead with this file rather than tidyCorpus2. For more on stemming, please consider Hvitfeldt and Slige<span class="citation">(<a href="#ref-hvitfeldt2021">2021</a>)</span>, which is available online.</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="working-with-text-a-case-study.html#cb243-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">33458</span>)</span>
<span id="cb243-2"><a href="working-with-text-a-case-study.html#cb243-2" tabindex="-1"></a>a2 <span class="ot">&lt;-</span> a1 <span class="sc">|&gt;</span> <span class="fu">filter</span> (selftext <span class="sc">!=</span> <span class="st">&quot;[removed]&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb243-3"><a href="working-with-text-a-case-study.html#cb243-3" tabindex="-1"></a>    <span class="fu">mutate</span> (<span class="at">epoch =</span> <span class="fu">case_when</span> (</span>
<span id="cb243-4"><a href="working-with-text-a-case-study.html#cb243-4" tabindex="-1"></a>        date <span class="sc">&lt;</span> <span class="st">&quot;2024-11-06 00:00:00&quot;</span> <span class="sc">~</span> <span class="st">&quot;Biden&quot;</span>,</span>
<span id="cb243-5"><a href="working-with-text-a-case-study.html#cb243-5" tabindex="-1"></a>        date <span class="sc">&gt;</span> <span class="st">&quot;2025-01-20 12:00:00&quot;</span> <span class="sc">~</span> <span class="st">&quot;Trump&quot;</span>,</span>
<span id="cb243-6"><a href="working-with-text-a-case-study.html#cb243-6" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;Lameduck&quot;</span></span>
<span id="cb243-7"><a href="working-with-text-a-case-study.html#cb243-7" tabindex="-1"></a>    ))</span>
<span id="cb243-8"><a href="working-with-text-a-case-study.html#cb243-8" tabindex="-1"></a>tidyCorpus0 <span class="ot">&lt;-</span> a2 <span class="sc">|&gt;</span> </span>
<span id="cb243-9"><a href="working-with-text-a-case-study.html#cb243-9" tabindex="-1"></a>    <span class="fu">unnest_tokens</span>(word, selftext, <span class="at">to_lower =</span> <span class="cn">FALSE</span>)</span>
<span id="cb243-10"><a href="working-with-text-a-case-study.html#cb243-10" tabindex="-1"></a>tidyCorpus1 <span class="ot">&lt;-</span> tidyCorpus0 <span class="sc">|&gt;</span> </span>
<span id="cb243-11"><a href="working-with-text-a-case-study.html#cb243-11" tabindex="-1"></a>    <span class="fu">mutate</span> (<span class="at">word =</span> <span class="fu">case_when</span>(</span>
<span id="cb243-12"><a href="working-with-text-a-case-study.html#cb243-12" tabindex="-1"></a><span class="co"># if changing a word to uppercase has no effect ...</span></span>
<span id="cb243-13"><a href="working-with-text-a-case-study.html#cb243-13" tabindex="-1"></a>        (<span class="fu">toupper</span>(word) <span class="sc">==</span> word) <span class="sc">&amp;</span> </span>
<span id="cb243-14"><a href="working-with-text-a-case-study.html#cb243-14" tabindex="-1"></a><span class="co"># amd the word is more than 1 character long, keep it as is</span></span>
<span id="cb243-15"><a href="working-with-text-a-case-study.html#cb243-15" tabindex="-1"></a>            <span class="fu">nchar</span>(word) <span class="sc">&gt;</span> <span class="dv">1</span> <span class="sc">~</span> word,</span>
<span id="cb243-16"><a href="working-with-text-a-case-study.html#cb243-16" tabindex="-1"></a><span class="co"># else change it to lowercase</span></span>
<span id="cb243-17"><a href="working-with-text-a-case-study.html#cb243-17" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="fu">tolower</span>(word)))</span>
<span id="cb243-18"><a href="working-with-text-a-case-study.html#cb243-18" tabindex="-1"></a></span>
<span id="cb243-19"><a href="working-with-text-a-case-study.html#cb243-19" tabindex="-1"></a><span class="co"># tidyCorpus2 gets rid of numbers and removes stop words</span></span>
<span id="cb243-20"><a href="working-with-text-a-case-study.html#cb243-20" tabindex="-1"></a>tidyCorpus2 <span class="ot">&lt;-</span> tidyCorpus1 <span class="sc">|&gt;</span> </span>
<span id="cb243-21"><a href="working-with-text-a-case-study.html#cb243-21" tabindex="-1"></a>    <span class="fu">anti_join</span>(stop_words) <span class="sc">|&gt;</span> </span>
<span id="cb243-22"><a href="working-with-text-a-case-study.html#cb243-22" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">word =</span> <span class="fu">gsub</span>(<span class="at">x =</span> word, </span>
<span id="cb243-23"><a href="working-with-text-a-case-study.html#cb243-23" tabindex="-1"></a>                       <span class="at">pattern =</span> <span class="st">&quot;[0-9]+|[[:punct:]]|</span><span class="sc">\\</span><span class="st">(.*</span><span class="sc">\\</span><span class="st">)&quot;</span>,</span>
<span id="cb243-24"><a href="working-with-text-a-case-study.html#cb243-24" tabindex="-1"></a>                       <span class="at">replacement =</span> <span class="st">&quot;&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb243-25"><a href="working-with-text-a-case-study.html#cb243-25" tabindex="-1"></a>    <span class="fu">filter</span> (word <span class="sc">!=</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb243-26"><a href="working-with-text-a-case-study.html#cb243-26" tabindex="-1"></a></span>
<span id="cb243-27"><a href="working-with-text-a-case-study.html#cb243-27" tabindex="-1"></a><span class="co"># tidyCorpus3 takes the additional step of stemming the data</span></span>
<span id="cb243-28"><a href="working-with-text-a-case-study.html#cb243-28" tabindex="-1"></a>tidyCorpus3 <span class="ot">&lt;-</span> tidyCorpus2 <span class="sc">|&gt;</span> </span>
<span id="cb243-29"><a href="working-with-text-a-case-study.html#cb243-29" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">word =</span> <span class="fu">wordStem</span>(word))</span></code></pre></div>
</div>
<div id="comparing-the-words-and-stems" class="section level2 hasAnchor" number="21.5">
<h2><span class="header-section-number">21.5</span> comparing the words and stems<a href="working-with-text-a-case-study.html#comparing-the-words-and-stems" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We reduce each of the the three tidy <em>corpora</em> (bodies of text) to simple frequency tables</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="working-with-text-a-case-study.html#cb244-1" tabindex="-1"></a>nwordsCorpus0 <span class="ot">&lt;-</span> tidyCorpus0 <span class="sc">|&gt;</span> <span class="fu">count</span> (word) <span class="sc">|&gt;</span> <span class="fu">nrow</span>()</span>
<span id="cb244-2"><a href="working-with-text-a-case-study.html#cb244-2" tabindex="-1"></a>nwordsCorpus1 <span class="ot">&lt;-</span> tidyCorpus1 <span class="sc">|&gt;</span> <span class="fu">count</span> (word) <span class="sc">|&gt;</span> <span class="fu">nrow</span>()</span>
<span id="cb244-3"><a href="working-with-text-a-case-study.html#cb244-3" tabindex="-1"></a>nwordsCorpus2 <span class="ot">&lt;-</span> tidyCorpus2 <span class="sc">|&gt;</span> <span class="fu">count</span> (word) <span class="sc">|&gt;</span> <span class="fu">nrow</span>()</span>
<span id="cb244-4"><a href="working-with-text-a-case-study.html#cb244-4" tabindex="-1"></a>nwordsCorpus3 <span class="ot">&lt;-</span> tidyCorpus3 <span class="sc">|&gt;</span> <span class="fu">count</span> (word) <span class="sc">|&gt;</span> <span class="fu">nrow</span>()</span></code></pre></div>
<p>Whereas there were 58154 words in the initial data, this drops to 49447 when we (mostly) represent all words as lower case. It drops further to 41586 when we remove numbers and stop words, and finally to 29338 when we stem the data.</p>
</div>
<div id="construction-of-differential-word-clouds" class="section level2 hasAnchor" number="21.6">
<h2><span class="header-section-number">21.6</span> Construction of differential word clouds<a href="working-with-text-a-case-study.html#construction-of-differential-word-clouds" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We first take the corpus and reshape it to a matrix with row names (words) and counts (one column for each group).</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="working-with-text-a-case-study.html#cb245-1" tabindex="-1"></a>wideCorpus2 <span class="ot">&lt;-</span> tidyCorpus2 <span class="sc">|&gt;</span></span>
<span id="cb245-2"><a href="working-with-text-a-case-study.html#cb245-2" tabindex="-1"></a>    <span class="fu">filter</span> (epoch <span class="sc">!=</span> <span class="st">&quot;Lameduck&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb245-3"><a href="working-with-text-a-case-study.html#cb245-3" tabindex="-1"></a>    <span class="fu">count</span>(epoch, word, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb245-4"><a href="working-with-text-a-case-study.html#cb245-4" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> epoch, <span class="at">values_from =</span> n, </span>
<span id="cb245-5"><a href="working-with-text-a-case-study.html#cb245-5" tabindex="-1"></a>                <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb245-6"><a href="working-with-text-a-case-study.html#cb245-6" tabindex="-1"></a>    <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;word&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb245-7"><a href="working-with-text-a-case-study.html#cb245-7" tabindex="-1"></a><span class="co"># filter out words that don&#39;t appear at least a few times in each group</span></span>
<span id="cb245-8"><a href="working-with-text-a-case-study.html#cb245-8" tabindex="-1"></a><span class="co"># and also removes words that are too rare to be useful for comparison</span></span>
<span id="cb245-9"><a href="working-with-text-a-case-study.html#cb245-9" tabindex="-1"></a>    <span class="fu">mutate</span> (<span class="at">mincount =</span> <span class="fu">pmin</span>(Biden, Trump)) <span class="sc">|&gt;</span> </span>
<span id="cb245-10"><a href="working-with-text-a-case-study.html#cb245-10" tabindex="-1"></a>    <span class="fu">filter</span> (mincount <span class="sc">&gt;</span> <span class="dv">4</span>) <span class="sc">|&gt;</span> </span>
<span id="cb245-11"><a href="working-with-text-a-case-study.html#cb245-11" tabindex="-1"></a>    <span class="fu">select</span> (<span class="sc">-</span>mincount) <span class="sc">|&gt;</span> </span>
<span id="cb245-12"><a href="working-with-text-a-case-study.html#cb245-12" tabindex="-1"></a>    <span class="fu">as.matrix</span>(<span class="at">rownames =</span> <span class="cn">TRUE</span>)  </span>
<span id="cb245-13"><a href="working-with-text-a-case-study.html#cb245-13" tabindex="-1"></a><span class="fu">head</span>(wideCorpus2,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##           Trump Biden
## federal    7200  2346
## employees  6351  1008
## people     4930  1246
## https      4801   762
## im         3975  3281</code></pre>
<p>The <code>comparison.cloud</code> function from the <code>wordcloud</code> package is used to show the greatest relative proportions of words in each group (in that function, the scale parameters will need to be adjusted to get the best visual representation).</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="working-with-text-a-case-study.html#cb247-1" tabindex="-1"></a><span class="fu">comparison.cloud</span>(wideCorpus2,</span>
<span id="cb247-2"><a href="working-with-text-a-case-study.html#cb247-2" tabindex="-1"></a>        <span class="at">scale =</span> <span class="fu">c</span>(<span class="fl">1.5</span>,.<span class="dv">5</span>),</span>
<span id="cb247-3"><a href="working-with-text-a-case-study.html#cb247-3" tabindex="-1"></a>        <span class="at">max.words=</span><span class="dv">100</span>,</span>
<span id="cb247-4"><a href="working-with-text-a-case-study.html#cb247-4" tabindex="-1"></a>        <span class="at">random.order=</span><span class="cn">FALSE</span>,</span>
<span id="cb247-5"><a href="working-with-text-a-case-study.html#cb247-5" tabindex="-1"></a>        <span class="at">rot.per =</span> <span class="dv">0</span>,</span>
<span id="cb247-6"><a href="working-with-text-a-case-study.html#cb247-6" tabindex="-1"></a>        <span class="at">use.r.layout=</span><span class="cn">FALSE</span>,</span>
<span id="cb247-7"><a href="working-with-text-a-case-study.html#cb247-7" tabindex="-1"></a>        <span class="at">family=</span><span class="st">&quot;sans&quot;</span>,</span>
<span id="cb247-8"><a href="working-with-text-a-case-study.html#cb247-8" tabindex="-1"></a>        <span class="at">title.size=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="DataSciLibArts_files/figure-html/unnamed-chunk-85-1.png" width="672" /></p>
<p>Many of the words which appear disproportionately in the Trump corpus (<em>employees, https, federal, government)</em> appear relatively neutral in emotional tone, although there are also terms such as <em>fired</em> and <em>resignation</em> here. On the Biden side, the abbreviation <em>GS</em> (for General Schedule, describing the level of various positions in civil service), together with <em>position, job, HR, step, hours</em>, and <em>supervisor</em> indicates that most posts refer to employment issues.</p>
<p>Interesting, but perhaps less than we might have expected. Will an analysis of two-word strings (bigrams) provide more insight?</p>
</div>
<div id="bigrams" class="section level2 hasAnchor" number="21.7">
<h2><span class="header-section-number">21.7</span> bigrams<a href="working-with-text-a-case-study.html#bigrams" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The comparison cloud illustrates differences in single-word occurrences between the Biden and Trump epochs in r/fedworkers. Here, we repeat the analysis, investigating two-word strings. Note that in order to remove stopwords and numbers, we fist combine adjacent words (tokens) into bigrams, then separate these into pairs of adjacent words, filter on each of these adjacent words, and rejoin them.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="working-with-text-a-case-study.html#cb248-1" tabindex="-1"></a>tidyBigrams <span class="ot">&lt;-</span> a2 <span class="sc">|&gt;</span> </span>
<span id="cb248-2"><a href="working-with-text-a-case-study.html#cb248-2" tabindex="-1"></a>    <span class="fu">filter</span> (epoch <span class="sc">!=</span> <span class="st">&quot;Lameduck&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb248-3"><a href="working-with-text-a-case-study.html#cb248-3" tabindex="-1"></a>    <span class="fu">unnest_tokens</span>(bigram, selftext, <span class="at">token =</span> <span class="st">&quot;ngrams&quot;</span>, <span class="at">n =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span> </span>
<span id="cb248-4"><a href="working-with-text-a-case-study.html#cb248-4" tabindex="-1"></a>    <span class="fu">separate</span>(bigram,<span class="fu">c</span>(<span class="st">&quot;word1&quot;</span>, <span class="st">&quot;word2&quot;</span>), <span class="at">sep =</span> <span class="st">&quot; &quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb248-5"><a href="working-with-text-a-case-study.html#cb248-5" tabindex="-1"></a>    <span class="fu">anti_join</span>(stop_words, <span class="at">by =</span> <span class="fu">join_by</span>(<span class="st">&quot;word1&quot;</span> <span class="sc">==</span> <span class="st">&quot;word&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb248-6"><a href="working-with-text-a-case-study.html#cb248-6" tabindex="-1"></a>    <span class="fu">anti_join</span>(stop_words, <span class="at">by =</span> <span class="fu">join_by</span>(<span class="st">&quot;word2&quot;</span> <span class="sc">==</span> <span class="st">&quot;word&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb248-7"><a href="working-with-text-a-case-study.html#cb248-7" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">word1 =</span> <span class="fu">gsub</span>(<span class="at">x =</span> word1, </span>
<span id="cb248-8"><a href="working-with-text-a-case-study.html#cb248-8" tabindex="-1"></a>                       <span class="at">pattern =</span> <span class="st">&quot;[0-9]+|[[:punct:]]|</span><span class="sc">\\</span><span class="st">(.*</span><span class="sc">\\</span><span class="st">)&quot;</span>,</span>
<span id="cb248-9"><a href="working-with-text-a-case-study.html#cb248-9" tabindex="-1"></a>                       <span class="at">replacement =</span> <span class="st">&quot;&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb248-10"><a href="working-with-text-a-case-study.html#cb248-10" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">word2 =</span> <span class="fu">gsub</span>(<span class="at">x =</span> word2, </span>
<span id="cb248-11"><a href="working-with-text-a-case-study.html#cb248-11" tabindex="-1"></a>                       <span class="at">pattern =</span> <span class="st">&quot;[0-9]+|[[:punct:]]|</span><span class="sc">\\</span><span class="st">(.*</span><span class="sc">\\</span><span class="st">)&quot;</span>,</span>
<span id="cb248-12"><a href="working-with-text-a-case-study.html#cb248-12" tabindex="-1"></a>                       <span class="at">replacement =</span> <span class="st">&quot;&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb248-13"><a href="working-with-text-a-case-study.html#cb248-13" tabindex="-1"></a>    <span class="fu">drop_na</span>() <span class="sc">|&gt;</span> </span>
<span id="cb248-14"><a href="working-with-text-a-case-study.html#cb248-14" tabindex="-1"></a>    <span class="fu">filter</span> (word1 <span class="sc">!=</span> <span class="st">&quot;&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb248-15"><a href="working-with-text-a-case-study.html#cb248-15" tabindex="-1"></a>    <span class="fu">filter</span> (word2 <span class="sc">!=</span> <span class="st">&quot;&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb248-16"><a href="working-with-text-a-case-study.html#cb248-16" tabindex="-1"></a>    <span class="fu">unite</span>(bigram, word1, word2, <span class="at">sep =</span> <span class="st">&quot; &quot;</span>)</span>
<span id="cb248-17"><a href="working-with-text-a-case-study.html#cb248-17" tabindex="-1"></a>bigramCounts <span class="ot">&lt;-</span> tidyBigrams <span class="sc">|&gt;</span>     </span>
<span id="cb248-18"><a href="working-with-text-a-case-study.html#cb248-18" tabindex="-1"></a>    <span class="fu">count</span>(epoch, bigram, <span class="at">sort =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb248-19"><a href="working-with-text-a-case-study.html#cb248-19" tabindex="-1"></a>    <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> epoch, <span class="at">values_from =</span> n, </span>
<span id="cb248-20"><a href="working-with-text-a-case-study.html#cb248-20" tabindex="-1"></a>                <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb248-21"><a href="working-with-text-a-case-study.html#cb248-21" tabindex="-1"></a>    <span class="fu">column_to_rownames</span>(<span class="at">var =</span> <span class="st">&quot;bigram&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb248-22"><a href="working-with-text-a-case-study.html#cb248-22" tabindex="-1"></a>    <span class="fu">as.matrix</span>(<span class="at">rownames =</span> <span class="cn">TRUE</span>) </span>
<span id="cb248-23"><a href="working-with-text-a-case-study.html#cb248-23" tabindex="-1"></a><span class="fu">comparison.cloud</span>(bigramCounts,</span>
<span id="cb248-24"><a href="working-with-text-a-case-study.html#cb248-24" tabindex="-1"></a>        <span class="at">scale =</span> <span class="fu">c</span>(<span class="fl">1.5</span>,.<span class="dv">5</span>),</span>
<span id="cb248-25"><a href="working-with-text-a-case-study.html#cb248-25" tabindex="-1"></a>        <span class="at">max.words=</span><span class="dv">100</span>,</span>
<span id="cb248-26"><a href="working-with-text-a-case-study.html#cb248-26" tabindex="-1"></a>        <span class="at">random.order=</span><span class="cn">FALSE</span>,</span>
<span id="cb248-27"><a href="working-with-text-a-case-study.html#cb248-27" tabindex="-1"></a>        <span class="at">rot.per =</span> <span class="dv">0</span>,</span>
<span id="cb248-28"><a href="working-with-text-a-case-study.html#cb248-28" tabindex="-1"></a>        <span class="at">use.r.layout=</span><span class="cn">FALSE</span>,</span>
<span id="cb248-29"><a href="working-with-text-a-case-study.html#cb248-29" tabindex="-1"></a>        <span class="at">family=</span><span class="st">&quot;sans&quot;</span>,</span>
<span id="cb248-30"><a href="working-with-text-a-case-study.html#cb248-30" tabindex="-1"></a>        <span class="at">title.size=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="DataSciLibArts_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
<p>Here, the language of the two epochs comes into clearer focus, with phrases such as <em>deferred resignation</em> characterizing the Trump epoch and the relatively benign <em>pay period</em> characterizing the Biden period.</p>
</div>
<div id="categories-of-words" class="section level2 hasAnchor" number="21.8">
<h2><span class="header-section-number">21.8</span> categories of words<a href="working-with-text-a-case-study.html#categories-of-words" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In my own research, I rely on a proprietary tool, <em>Linguistic Inquiry and Word Count.</em> Though LIWC can be run within R on a machine that has the license for the software, here I run the program externally, then reimport it into R.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="working-with-text-a-case-study.html#cb249-1" tabindex="-1"></a><span class="fu">write_csv</span>(a2, <span class="st">&quot;data/fedworkersposts.csv&quot;</span>)</span>
<span id="cb249-2"><a href="working-with-text-a-case-study.html#cb249-2" tabindex="-1"></a><span class="co"># we run LIWC outside of R here. </span></span>
<span id="cb249-3"><a href="working-with-text-a-case-study.html#cb249-3" tabindex="-1"></a><span class="co"># the code is run on the raw data files</span></span>
<span id="cb249-4"><a href="working-with-text-a-case-study.html#cb249-4" tabindex="-1"></a>fedworkersLIWC <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/fedworkersLIWC.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="code-for-assessing-liwc-effect-sizes-between-2-groups" class="section level2 hasAnchor" number="21.9">
<h2><span class="header-section-number">21.9</span> Code for assessing LIWC effect sizes between 2 groups<a href="working-with-text-a-case-study.html#code-for-assessing-liwc-effect-sizes-between-2-groups" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are many measures, or categories, in LIWC. In order to assess the statistical significance of differecnces between the Biden and Trump epochs on LIWC, the simplest approach is to adjust for the number of comparisons using the Bonferroni correction. The number of LIWC categories is 117, so the Bonferroni p-value should be .05/117 = .000427.</p>
<p>This chunk uses three different libraries describe function from the psych package to get means, standard deviations, and sample sizes for each LIWC category. Then it computes the effect sizes and associated statistics using the mes function from the compute.es package and makes tables for the LIWC variables with the largest effects.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="working-with-text-a-case-study.html#cb250-1" tabindex="-1"></a>BonferroniP <span class="ot">&lt;-</span> (.<span class="dv">05</span><span class="sc">/</span><span class="dv">117</span>) <span class="co"># 117 is the number of LIWC categories# simple descriptives</span></span>
<span id="cb250-2"><a href="working-with-text-a-case-study.html#cb250-2" tabindex="-1"></a></span>
<span id="cb250-3"><a href="working-with-text-a-case-study.html#cb250-3" tabindex="-1"></a>BidenEpoch <span class="ot">&lt;-</span> fedworkersLIWC <span class="sc">|&gt;</span> </span>
<span id="cb250-4"><a href="working-with-text-a-case-study.html#cb250-4" tabindex="-1"></a>    <span class="fu">filter</span> (epoch <span class="sc">==</span> <span class="st">&quot;Biden&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb250-5"><a href="working-with-text-a-case-study.html#cb250-5" tabindex="-1"></a>    <span class="fu">select</span>(WC<span class="sc">:</span>OtherP) <span class="sc">|&gt;</span> </span>
<span id="cb250-6"><a href="working-with-text-a-case-study.html#cb250-6" tabindex="-1"></a>    <span class="fu">describe</span>() <span class="sc">|&gt;</span> <span class="co"># from the psych package</span></span>
<span id="cb250-7"><a href="working-with-text-a-case-study.html#cb250-7" tabindex="-1"></a>    <span class="fu">select</span>(<span class="at">BidenN=</span>n, <span class="at">BidenM =</span> mean, <span class="at">BidenSD =</span> sd) <span class="sc">|&gt;</span> </span>
<span id="cb250-8"><a href="working-with-text-a-case-study.html#cb250-8" tabindex="-1"></a>    <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb250-9"><a href="working-with-text-a-case-study.html#cb250-9" tabindex="-1"></a>TrumpEpoch <span class="ot">&lt;-</span> fedworkersLIWC <span class="sc">|&gt;</span></span>
<span id="cb250-10"><a href="working-with-text-a-case-study.html#cb250-10" tabindex="-1"></a>    <span class="fu">filter</span> (epoch <span class="sc">==</span> <span class="st">&quot;Trump&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb250-11"><a href="working-with-text-a-case-study.html#cb250-11" tabindex="-1"></a>    <span class="fu">select</span>(WC<span class="sc">:</span>OtherP) <span class="sc">|&gt;</span> </span>
<span id="cb250-12"><a href="working-with-text-a-case-study.html#cb250-12" tabindex="-1"></a>    <span class="fu">describe</span>() <span class="sc">|&gt;</span></span>
<span id="cb250-13"><a href="working-with-text-a-case-study.html#cb250-13" tabindex="-1"></a>    <span class="fu">select</span>(<span class="at">TrumpN=</span>n, <span class="at">TrumpM =</span> mean, <span class="at">TrumpSD =</span> sd) <span class="sc">|&gt;</span> </span>
<span id="cb250-14"><a href="working-with-text-a-case-study.html#cb250-14" tabindex="-1"></a>    <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb250-15"><a href="working-with-text-a-case-study.html#cb250-15" tabindex="-1"></a>poststats <span class="ot">&lt;-</span> BidenEpoch <span class="sc">|&gt;</span> </span>
<span id="cb250-16"><a href="working-with-text-a-case-study.html#cb250-16" tabindex="-1"></a>    <span class="fu">bind_cols</span> (TrumpEpoch)</span>
<span id="cb250-17"><a href="working-with-text-a-case-study.html#cb250-17" tabindex="-1"></a><span class="co"># from the compare.es package.</span></span>
<span id="cb250-18"><a href="working-with-text-a-case-study.html#cb250-18" tabindex="-1"></a>Effects <span class="ot">&lt;-</span> <span class="fu">mes</span>(poststats[,<span class="dv">2</span>], </span>
<span id="cb250-19"><a href="working-with-text-a-case-study.html#cb250-19" tabindex="-1"></a>               poststats[,<span class="dv">5</span>],</span>
<span id="cb250-20"><a href="working-with-text-a-case-study.html#cb250-20" tabindex="-1"></a>               poststats[,<span class="dv">3</span>], </span>
<span id="cb250-21"><a href="working-with-text-a-case-study.html#cb250-21" tabindex="-1"></a>               poststats[,<span class="dv">6</span>],</span>
<span id="cb250-22"><a href="working-with-text-a-case-study.html#cb250-22" tabindex="-1"></a>               poststats[,<span class="dv">1</span>],poststats[,<span class="dv">4</span>],</span>
<span id="cb250-23"><a href="working-with-text-a-case-study.html#cb250-23" tabindex="-1"></a>               <span class="at">level =</span> BonferroniP,</span>
<span id="cb250-24"><a href="working-with-text-a-case-study.html#cb250-24" tabindex="-1"></a>               <span class="at">verbose =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb250-25"><a href="working-with-text-a-case-study.html#cb250-25" tabindex="-1"></a>    <span class="fu">select</span>(d, l.d, u.d, pval.d)</span>
<span id="cb250-26"><a href="working-with-text-a-case-study.html#cb250-26" tabindex="-1"></a>LIWCSummary <span class="ot">&lt;-</span> poststats <span class="sc">|&gt;</span> </span>
<span id="cb250-27"><a href="working-with-text-a-case-study.html#cb250-27" tabindex="-1"></a>    <span class="fu">bind_cols</span>(Effects) <span class="sc">|&gt;</span></span>
<span id="cb250-28"><a href="working-with-text-a-case-study.html#cb250-28" tabindex="-1"></a>    <span class="fu">select</span>(<span class="sc">-</span>BidenN, <span class="sc">-</span>TrumpN) <span class="sc">|&gt;</span> </span>
<span id="cb250-29"><a href="working-with-text-a-case-study.html#cb250-29" tabindex="-1"></a>    <span class="fu">write_csv</span>(<span class="st">&quot;data/LIWCeffects.csv&quot;</span>)</span>
<span id="cb250-30"><a href="working-with-text-a-case-study.html#cb250-30" tabindex="-1"></a></span>
<span id="cb250-31"><a href="working-with-text-a-case-study.html#cb250-31" tabindex="-1"></a>Nsignificant <span class="ot">&lt;-</span> Effects <span class="sc">|&gt;</span> </span>
<span id="cb250-32"><a href="working-with-text-a-case-study.html#cb250-32" tabindex="-1"></a>    <span class="fu">mutate</span> (<span class="at">sig =</span> <span class="fu">case_when</span> (pval.d <span class="sc">&lt;</span> BonferroniP <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb250-33"><a href="working-with-text-a-case-study.html#cb250-33" tabindex="-1"></a>                             <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb250-34"><a href="working-with-text-a-case-study.html#cb250-34" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">sum =</span> <span class="fu">sum</span>(sig)) <span class="sc">|&gt;</span> </span>
<span id="cb250-35"><a href="working-with-text-a-case-study.html#cb250-35" tabindex="-1"></a>    <span class="fu">as.numeric</span>()</span>
<span id="cb250-36"><a href="working-with-text-a-case-study.html#cb250-36" tabindex="-1"></a>BidenN <span class="ot">&lt;-</span> <span class="fu">min</span>(poststats<span class="sc">$</span>BidenN)</span>
<span id="cb250-37"><a href="working-with-text-a-case-study.html#cb250-37" tabindex="-1"></a>TrumpN <span class="ot">&lt;-</span> <span class="fu">min</span>(poststats<span class="sc">$</span>TrumpN)</span>
<span id="cb250-38"><a href="working-with-text-a-case-study.html#cb250-38" tabindex="-1"></a>LIWCSummary <span class="sc">|&gt;</span> </span>
<span id="cb250-39"><a href="working-with-text-a-case-study.html#cb250-39" tabindex="-1"></a>    <span class="fu">slice_max</span>(d, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span> </span>
<span id="cb250-40"><a href="working-with-text-a-case-study.html#cb250-40" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;LIWC categories in r/fedworkers most associated with the Biden era&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb250-41"><a href="working-with-text-a-case-study.html#cb250-41" tabindex="-1"></a>    <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb250-42"><a href="working-with-text-a-case-study.html#cb250-42" tabindex="-1"></a>    <span class="fu">add_footnote</span>(<span class="fu">paste0</span>(</span>
<span id="cb250-43"><a href="working-with-text-a-case-study.html#cb250-43" tabindex="-1"></a>        <span class="st">&quot;Note: BidenNs &gt;= &quot;</span>,</span>
<span id="cb250-44"><a href="working-with-text-a-case-study.html#cb250-44" tabindex="-1"></a>        <span class="fu">min</span>(poststats<span class="sc">$</span>BidenN),</span>
<span id="cb250-45"><a href="working-with-text-a-case-study.html#cb250-45" tabindex="-1"></a>        <span class="st">&quot; TrumpNs &gt;= &quot;</span>,</span>
<span id="cb250-46"><a href="working-with-text-a-case-study.html#cb250-46" tabindex="-1"></a>        <span class="fu">min</span>(poststats<span class="sc">$</span>TrumpN)))</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-88">Table 21.1: </span><span id="tab:unnamed-chunk-88">Table 21.2: </span>LIWC categories in r/fedworkers most associated with the Biden era
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
BidenM
</th>
<th style="text-align:right;">
BidenSD
</th>
<th style="text-align:right;">
TrumpM
</th>
<th style="text-align:right;">
TrumpSD
</th>
<th style="text-align:right;">
d
</th>
<th style="text-align:right;">
l.d
</th>
<th style="text-align:right;">
u.d
</th>
<th style="text-align:right;">
pval.d
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Authentic
</td>
<td style="text-align:right;">
72.81
</td>
<td style="text-align:right;">
31.07
</td>
<td style="text-align:right;">
52.05
</td>
<td style="text-align:right;">
36.62
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
i
</td>
<td style="text-align:right;">
6.33
</td>
<td style="text-align:right;">
4.44
</td>
<td style="text-align:right;">
3.68
</td>
<td style="text-align:right;">
4.64
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Tone
</td>
<td style="text-align:right;">
41.36
</td>
<td style="text-align:right;">
29.32
</td>
<td style="text-align:right;">
31.28
</td>
<td style="text-align:right;">
28.63
</td>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:right;">
0.35
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Dic
</td>
<td style="text-align:right;">
89.69
</td>
<td style="text-align:right;">
7.90
</td>
<td style="text-align:right;">
86.08
</td>
<td style="text-align:right;">
12.16
</td>
<td style="text-align:right;">
0.33
</td>
<td style="text-align:right;">
0.33
</td>
<td style="text-align:right;">
0.33
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
function
</td>
<td style="text-align:right;">
54.47
</td>
<td style="text-align:right;">
10.41
</td>
<td style="text-align:right;">
50.53
</td>
<td style="text-align:right;">
15.62
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
money
</td>
<td style="text-align:right;">
1.55
</td>
<td style="text-align:right;">
2.50
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
2.23
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Linguistic
</td>
<td style="text-align:right;">
69.16
</td>
<td style="text-align:right;">
10.82
</td>
<td style="text-align:right;">
65.14
</td>
<td style="text-align:right;">
16.25
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0.27
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
conj
</td>
<td style="text-align:right;">
6.46
</td>
<td style="text-align:right;">
3.26
</td>
<td style="text-align:right;">
5.52
</td>
<td style="text-align:right;">
3.79
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
time
</td>
<td style="text-align:right;">
5.33
</td>
<td style="text-align:right;">
4.21
</td>
<td style="text-align:right;">
4.23
</td>
<td style="text-align:right;">
4.36
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
achieve
</td>
<td style="text-align:right;">
1.67
</td>
<td style="text-align:right;">
2.02
</td>
<td style="text-align:right;">
1.23
</td>
<td style="text-align:right;">
1.87
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Lifestyle
</td>
<td style="text-align:right;">
6.82
</td>
<td style="text-align:right;">
4.34
</td>
<td style="text-align:right;">
5.75
</td>
<td style="text-align:right;">
4.81
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup>a</sup> Note: BidenNs &gt;= 9010 TrumpNs &gt;= 19068
</td>
</tr>
</tfoot>
</table>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="working-with-text-a-case-study.html#cb251-1" tabindex="-1"></a>LIWCSummary <span class="sc">|&gt;</span> </span>
<span id="cb251-2"><a href="working-with-text-a-case-study.html#cb251-2" tabindex="-1"></a>    <span class="fu">slice_min</span>(d, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span> </span>
<span id="cb251-3"><a href="working-with-text-a-case-study.html#cb251-3" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;LIWC categories in r/fedworkers most associated with the Trump era&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb251-4"><a href="working-with-text-a-case-study.html#cb251-4" tabindex="-1"></a>    <span class="fu">kable_styling</span>() <span class="sc">%&gt;%</span></span>
<span id="cb251-5"><a href="working-with-text-a-case-study.html#cb251-5" tabindex="-1"></a>    <span class="fu">add_footnote</span>(<span class="fu">paste0</span>(</span>
<span id="cb251-6"><a href="working-with-text-a-case-study.html#cb251-6" tabindex="-1"></a>        <span class="st">&quot;Note: BidenNs &gt;= &quot;</span>,</span>
<span id="cb251-7"><a href="working-with-text-a-case-study.html#cb251-7" tabindex="-1"></a>        <span class="fu">min</span>(poststats<span class="sc">$</span>BidenN),</span>
<span id="cb251-8"><a href="working-with-text-a-case-study.html#cb251-8" tabindex="-1"></a>        <span class="st">&quot; TrumpNs &gt;= &quot;</span>,</span>
<span id="cb251-9"><a href="working-with-text-a-case-study.html#cb251-9" tabindex="-1"></a>        <span class="fu">min</span>(poststats<span class="sc">$</span>TrumpN)))</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-88">Table 21.1: </span><span id="tab:unnamed-chunk-88">Table 21.1: </span>LIWC categories in r/fedworkers most associated with the Trump era
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
BidenM
</th>
<th style="text-align:right;">
BidenSD
</th>
<th style="text-align:right;">
TrumpM
</th>
<th style="text-align:right;">
TrumpSD
</th>
<th style="text-align:right;">
d
</th>
<th style="text-align:right;">
l.d
</th>
<th style="text-align:right;">
u.d
</th>
<th style="text-align:right;">
pval.d
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Clout
</td>
<td style="text-align:right;">
23.33
</td>
<td style="text-align:right;">
28.67
</td>
<td style="text-align:right;">
42.22
</td>
<td style="text-align:right;">
33.36
</td>
<td style="text-align:right;">
-0.59
</td>
<td style="text-align:right;">
-0.59
</td>
<td style="text-align:right;">
-0.59
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Culture
</td>
<td style="text-align:right;">
1.26
</td>
<td style="text-align:right;">
2.39
</td>
<td style="text-align:right;">
2.70
</td>
<td style="text-align:right;">
4.10
</td>
<td style="text-align:right;">
-0.40
</td>
<td style="text-align:right;">
-0.40
</td>
<td style="text-align:right;">
-0.40
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
we
</td>
<td style="text-align:right;">
0.46
</td>
<td style="text-align:right;">
1.29
</td>
<td style="text-align:right;">
1.14
</td>
<td style="text-align:right;">
2.34
</td>
<td style="text-align:right;">
-0.33
</td>
<td style="text-align:right;">
-0.33
</td>
<td style="text-align:right;">
-0.33
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
tone_neg
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
2.05
</td>
<td style="text-align:right;">
2.05
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
-0.31
</td>
<td style="text-align:right;">
-0.31
</td>
<td style="text-align:right;">
-0.31
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
tech
</td>
<td style="text-align:right;">
0.56
</td>
<td style="text-align:right;">
1.68
</td>
<td style="text-align:right;">
1.44
</td>
<td style="text-align:right;">
3.23
</td>
<td style="text-align:right;">
-0.31
</td>
<td style="text-align:right;">
-0.31
</td>
<td style="text-align:right;">
-0.31
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Social
</td>
<td style="text-align:right;">
8.76
</td>
<td style="text-align:right;">
5.96
</td>
<td style="text-align:right;">
10.92
</td>
<td style="text-align:right;">
7.60
</td>
<td style="text-align:right;">
-0.30
</td>
<td style="text-align:right;">
-0.30
</td>
<td style="text-align:right;">
-0.30
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
socrefs
</td>
<td style="text-align:right;">
4.93
</td>
<td style="text-align:right;">
4.43
</td>
<td style="text-align:right;">
6.47
</td>
<td style="text-align:right;">
5.37
</td>
<td style="text-align:right;">
-0.30
</td>
<td style="text-align:right;">
-0.30
</td>
<td style="text-align:right;">
-0.30
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
affiliation
</td>
<td style="text-align:right;">
1.13
</td>
<td style="text-align:right;">
2.31
</td>
<td style="text-align:right;">
1.91
</td>
<td style="text-align:right;">
3.02
</td>
<td style="text-align:right;">
-0.28
</td>
<td style="text-align:right;">
-0.28
</td>
<td style="text-align:right;">
-0.28
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
power
</td>
<td style="text-align:right;">
1.63
</td>
<td style="text-align:right;">
2.55
</td>
<td style="text-align:right;">
2.48
</td>
<td style="text-align:right;">
3.29
</td>
<td style="text-align:right;">
-0.28
</td>
<td style="text-align:right;">
-0.28
</td>
<td style="text-align:right;">
-0.28
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
emo_neg
</td>
<td style="text-align:right;">
0.56
</td>
<td style="text-align:right;">
1.47
</td>
<td style="text-align:right;">
1.28
</td>
<td style="text-align:right;">
3.13
</td>
<td style="text-align:right;">
-0.27
</td>
<td style="text-align:right;">
-0.27
</td>
<td style="text-align:right;">
-0.27
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup>a</sup> Note: BidenNs &gt;= 9010 TrumpNs &gt;= 19068
</td>
</tr>
</tfoot>
</table>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="working-with-text-a-case-study.html#cb252-1" tabindex="-1"></a>LIWCSummary <span class="sc">|&gt;</span> </span>
<span id="cb252-2"><a href="working-with-text-a-case-study.html#cb252-2" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(d)) <span class="sc">|&gt;</span> </span>
<span id="cb252-3"><a href="working-with-text-a-case-study.html#cb252-3" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">|&gt;</span> </span>
<span id="cb252-4"><a href="working-with-text-a-case-study.html#cb252-4" tabindex="-1"></a>    <span class="fu">kable</span>()</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="17%" />
<col width="11%" />
<col width="12%" />
<col width="11%" />
<col width="12%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">BidenM</th>
<th align="right">BidenSD</th>
<th align="right">TrumpM</th>
<th align="right">TrumpSD</th>
<th align="right">d</th>
<th align="right">l.d</th>
<th align="right">u.d</th>
<th align="right">pval.d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Authentic</td>
<td align="right">72.81</td>
<td align="right">31.07</td>
<td align="right">52.05</td>
<td align="right">36.62</td>
<td align="right">0.59</td>
<td align="right">0.59</td>
<td align="right">0.59</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">i</td>
<td align="right">6.33</td>
<td align="right">4.44</td>
<td align="right">3.68</td>
<td align="right">4.64</td>
<td align="right">0.58</td>
<td align="right">0.58</td>
<td align="right">0.58</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Tone</td>
<td align="right">41.36</td>
<td align="right">29.32</td>
<td align="right">31.28</td>
<td align="right">28.63</td>
<td align="right">0.35</td>
<td align="right">0.35</td>
<td align="right">0.35</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">Dic</td>
<td align="right">89.69</td>
<td align="right">7.90</td>
<td align="right">86.08</td>
<td align="right">12.16</td>
<td align="right">0.33</td>
<td align="right">0.33</td>
<td align="right">0.33</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">function</td>
<td align="right">54.47</td>
<td align="right">10.41</td>
<td align="right">50.53</td>
<td align="right">15.62</td>
<td align="right">0.28</td>
<td align="right">0.28</td>
<td align="right">0.28</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">money</td>
<td align="right">1.55</td>
<td align="right">2.50</td>
<td align="right">0.91</td>
<td align="right">2.23</td>
<td align="right">0.28</td>
<td align="right">0.28</td>
<td align="right">0.28</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">Linguistic</td>
<td align="right">69.16</td>
<td align="right">10.82</td>
<td align="right">65.14</td>
<td align="right">16.25</td>
<td align="right">0.27</td>
<td align="right">0.27</td>
<td align="right">0.27</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">conj</td>
<td align="right">6.46</td>
<td align="right">3.26</td>
<td align="right">5.52</td>
<td align="right">3.79</td>
<td align="right">0.26</td>
<td align="right">0.26</td>
<td align="right">0.26</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">time</td>
<td align="right">5.33</td>
<td align="right">4.21</td>
<td align="right">4.23</td>
<td align="right">4.36</td>
<td align="right">0.26</td>
<td align="right">0.26</td>
<td align="right">0.26</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">achieve</td>
<td align="right">1.67</td>
<td align="right">2.02</td>
<td align="right">1.23</td>
<td align="right">1.87</td>
<td align="right">0.23</td>
<td align="right">0.23</td>
<td align="right">0.23</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>There are just over 19000 posts in the (roughly four month long) Trump epoch, and just over 9000 in the (roughly ten months long) Biden epoch. Judging from the number of posts, the <em>r/fedworkers</em> subreddit has been substantially more active since the Trump presidency began.</p>
<p>In comparisons of the two “epochs,” the LIWC categories which were particularly characteristic of the Biden posts included <em>Authentic,</em> a summary variable indicating apparent honesty or genuineness, and <em>I</em>, including first-person singular pronouns <span class="citation">(<a href="#ref-boyd2022">Ryan L. Boyd et al. 2022</a>)</span>. For each of these, the effect size (difference in standard deviations between the two distributions), was more than .5, indicating a moderate effect. The LIWC categories which were particularly characteristic of the Trump posts included <em>Clout,</em> a summary category of words associated with leadership or status, followed by <em>Culture,</em> which includes language about politics, technology, and ethnicity, and <em>we</em>, second-person singular pronouns)<em>.</em> The shift from the first-person singular to plural is what we might expect in a community of individuals subjectively under siege. Altogether, of the 117 LIWC Categories, 98 showed a statistically significant difference between the two epochs.</p>
<p>These analyses support the argument presented in the <em>Times</em> article referenced above, including that the r/<em>fedworkers</em> subreddit had grown, in the Trump epoch, into a supportive community (shift from <em>i</em> to <em>we</em>), in which workers were sharing anxieties (LIWC categories such as <em>emo_neg</em> and <em>tone_neg</em>).</p>
</div>
<div id="exercise-what-would-you-do-next" class="section level2 hasAnchor" number="21.10">
<h2><span class="header-section-number">21.10</span> exercise: what would you do next?<a href="working-with-text-a-case-study.html#exercise-what-would-you-do-next" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter has provided a brief example of how to work with text from Reddit. If you were to work with these data, what would you do next? If you were to work with another dataset, what would it look like, what would you expect to find, and how would you study it?</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-boyd2022" class="csl-entry">
Boyd, Ryan L, Ashwini Ashokkumar, Sarah Seraj, and James W Pennebaker. 2022. <span>“The Development and Psychometric Properties of LIWC-22.”</span> <em>Austin, TX: University of Texas at Austin</em> 10: 1–47.
</div>
<div id="ref-hvitfeldt2021" class="csl-entry">
Hvitfeldt, Emil, and Julia Silge. 2021. <em>Supervised Machine Learning for Text Analysis in <span>R</span></em>. <span>Chapman and Hall/CRC</span>.
</div>
<div id="ref-pennebaker2014" class="csl-entry">
Pennebaker, James W., Cindy K. Chung, Joey Frazee, Gary M. Lavergne, and David I. Beaver. 2014. <span>“When <span>Small Words Foretell Academic Success</span>: <span>The Case</span> of <span>College Admissions Essays</span>.”</span> Edited by Qiyong Gong. <em>PLoS ONE</em> 9 (12): e115844. <a href="https://doi.org/10/f6z8q5">https://doi.org/10/f6z8q5</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="4">
<li id="fn4"><p>Reddit is an electronic discussion board or website which is structured as a set of communities or subreddits; each subreddit includes posts, and, typically, submitted by users (redditors).<a href="working-with-text-a-case-study.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>The selection of posts rather than comments is somewhat arbitrary; one reason for examining posts is that the simple number of comments in the period under study would be relatively unwieldy.<a href="working-with-text-a-case-study.html#fnref5" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="machine-learning-chihuahuas-vs-muffins-and-other-distinctions-and-ideas.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="an-introduction-to-networks.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
